collections:
  Recently Released:
    smart_filter:
      all:
        release: 365
      sort_by: added.desc
    sort_title: ++_1.5Recently Released
    name_mapping: Recently Released
    only_run_on_create: true
    summary: Movies released in the last 365 days
