collections:
  New Releases:
    smart_filter:
      all:
        release: 365
      sort_by: added.desc
    sort_title: '!_First New Releases'
    name_mapping: New Releases
    only_run_on_create: true
    summary: Movies released in the last year
  Now Playing:
    smart_label: release.asc
    sort_title: '!_First Now Playing'
    plex_search:
      all:
        release.after: 01/01/2024
    filters:
      filepath.regex:
        - (?i)\bCAM\b
        - (?i)\bTELESYNC\b
    summay: Now playing in theaters
