collections:
  New Release:
    smart_filter:
      all:
        release: 365
      sort_by: added.desc
    sort_title: '!_First New Release'
    only_run_on_create: true
    summary: Movies released in the last year
