templates:
  Studio:
    tmdb_company: <<company>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio + Network:
    tmdb_company: <<company>>
    tmdb_network: <<network>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: custom
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    sync_mode: sync
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Disney:
    template:
      name: Studio
      company: '2, 3, 6125, 3166'
      list: disney
      summary: It was all started with a mouse
  Disneynature:
    template:
      name: Studio
      company: 4436
      summary: >-
        Disneynature is an independent film studio that specializes in the
        production of nature documentary films for The Walt Disney Studios. The
        production company was founded on April 21, 2008, and is headquartered
        in Paris, France.
  National Geographic:
    template:
      name: Studio - Trakt List
      list: national-geographic
      summary: >-
        National Geographic is an American pay television network and flagship
        channel owned by National Geographic Partners, a joint venture between
        The Walt Disney Company and the National Geographic Society, with the
        operational management handled by Walt Disney Television.
