templates:
  Studio:
    collection_order: release
    collection_mode: hide_items
    tmdb_company: <<company>>
    sort_title: ++_6<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Universal Monsters:
    template:
      name: Studios - Trakt List
      list: universal-monsters
      summary: >-
        Universal Monsters is a media franchise based on a series of horror
        films primarily produced by Universal Pictures from the 1930s to the
        1950s.
