templates:
  Studio:
    tmdb_company: <<company>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - list
      - summary
    trakt_list: <<list>>
    summary: <<summary>>
  Studio - Smart:
    smart_filter:
      any:
        studio: <<studio>>
      sort_by: release.desc
    sort_title: ++_4<<collection_name>>
    only_run_on_create: true
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: <<list>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: <<list>>
    collection_order: custom
    collection_mode: show_items
    sort_title: ++_4<<collection_name>>
    sync_mode: sync
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
collections:
  Universal Monsters:
    template:
      name: Studios - Trakt List
      list: 'https://trakt.tv/users/goape/lists/universal-monsters'
      summary: >-
        Universal Monsters is a media franchise based on a series of horror
        films primarily produced by Universal Pictures from the 1930s to the
        1950s.
