templates:
  Studio:
    tmdb_company: <<company>>
    smart_label: year.asc
    sort_title: ++_4<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: <<list>>
    summary: <<summary>>
  Studio - Smart:
    smart_filter:
      any:
        studio: <<studio>>
      sort_by: release.desc
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: <<list>>
    smart_label: year.asc
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: <<list>>
    collection_order: custom
    collection_mode: show_items
    sync_mode: sync
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    smart_label: year.asc
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  A24:
    template:
      name: Studio
      company: 41077
      list: 'https://trakt.tv/users/goape/lists/a24'
      summary: >-
        A24 is an American independent entertainment company founded on August
        20, 2012, by Daniel Katz, David Fenkel, and John Hodges that specializes
        in film and television production, as well as film distribution. It is
        based in New York City.
  DC:
    template:
      name: Studio
      company: 9993
      list: 'https://trakt.tv/users/goape/lists/dc'
      summary: >-
        DC Films is an American film studio that is a subsidiary of Warner Bros.
        through the Warner Bros. Pictures Group, dedicated to the production of
        films based on characters from DC Entertainment.
  DC Animated Originals:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/dc-animated'
      summary: >-
        The DC Animated Universe (DCAU; also referred to as the Timmverse or
        Diniverse by fans) is a shared universe of superhero-based animated
        television series, produced by Warner Bros. Animation and based on
        characters that appear in American comic books published by DC Comics.
  Hammer Films:
    template:
      name: Studio - Smart
      studio: Hammer Film Productions
      summary: >-
        Hammer Film Productions Ltd. is a British film production company based
        in London. Founded in 1934, the company is best known for a series of
        Gothic horror and fantasy films made from the mid-1950s until the 1970s.
        Many of these involved classic horror characters such as Baron Victor
        Frankenstein, Count Dracula, and the Mummy, which Hammer reintroduced to
        audiences by filming them in vivid colour for the first time.
  LEGO:
    template:
      name: Studio - Search
      title: 'LEGO, Lego'
      summary: The bane of your foot's existence.
  Marvel:
    template:
      name: Studio
      company: '7505, 19551, 420, 11106, 13252, 38679'
      list: 'https://trakt.tv/users/goape/lists/marvel'
      summary: With great power comes great responsibility
  Marvel Animation:
    template:
      name: Studio
      company: 13252
      list: 'https://trakt.tv/users/goape/lists/marvel-animation'
      summary: >-
        Marvel Animation, Inc. (originally the home entertainment and TV
        production division of Marvel Studios and also referred to as Marvel
        Family Entertainment) is an American animation production company. The
        Marvel Studios subsidiary was incorporated on January 25, 2008 to direct
        Marvel's efforts in animation and home entertainment markets. The
        incorporated Marvel Animation included then ongoing animation efforts by
        Marvel Studios with Lionsgate and Nickelodeon. Marvel Animation operated
        under Marvel Studios, a subsidiary of Walt Disney Studios, a division of
        The Walt Disney Company.
  Nickelodeon:
    template:
      name: Studio
      company: '4859, 5371, 2348'
      list: 'https://trakt.tv/users/goape/lists/nickelodeon'
      summary: 'Nick, Nick, Nick, Nick, Ni-, Nick, Nick, Nick Nickelodeon'
  Sony Pictures Animation:
    template:
      name: Studio
      company: 2251
      summary: >-
        Sony Pictures Animation Inc. is an American animation studio owned by
        Sony Entertainment's Sony Pictures Entertainment through their Motion
        Picture Group division and founded on May 9, 2002.
  Walt Disney Pictures:
    template:
      name: Studio - Smart
      studio: Walt Disney Pictures
      summary: >-
        Walt Disney Pictures is an American film production studio of The Walt
        Disney Studios, which is owned by The Walt Disney Company. The studio is
        the flagship producer of live-action feature films within the Walt
        Disney Studios unit, and is based at the Walt Disney Studios in Burbank,
        California. Animated films produced by Walt Disney Animation Studios and
        Pixar Animation Studios are also released under this brand. Walt Disney
        Studios Motion Pictures distributes and markets the films produced by
        Walt Disney Pictures.
    sort_title: ++_4Disney Pictures
