templates:
  Studio:
    tmdb_company: <<company>>
    collection_order: release
    collection_mode: hide_items
    default:
      sort_title: ++_6<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    default:
      sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    default:
      sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Disney Filtered:
    template:
      name: Studio
      company: '2, 3, 6125, 3166, 3475, 670'
      list: disney
    name: Disney
    sync_mode: sync
    plex_search:
      title:
        - The Wonderful World of Disney
        - Disneyland
    show_filtered: true
    title.not:
      - Power Rangers
      - Storm of the Century
