templates:
  Studio:
    tmdb_company: <<company>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - list
      - summary
    trakt_list: <<list>>
    summary: <<summary>>
  Studio - Smart:
    smart_filter:
      any:
        studio: <<studio>>
      sort_by: release.desc
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: <<list>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: <<list>>
    collection_order: custom
    collection_mode: show_items
    sort_title: ++_4<<collection_name>>
    sync_mode: sync
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
collections:
  Disney:
    template:
      name: Studio
      company: '2, 3, 6125, 3166, 3475, 670'
      list: 'https://trakt.tv/users/goape/lists/disney'
      summary: It was all started with a mouse
  Disney Channel Original Movies:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/disney-channel-original-movies'
      summary: >-
        Disney Channel Original Movies or DCOM (formerly a "Zoog Disney Channel
        Movie") is any movie that is produced under the Disney Channel canon.
        They have been made at a rate of at once a year since 1999.
    sort_title: ++_6Disney2 Channel Original Movies
  Disney Shorts:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/disney-animated-shorts'
      summary: It was all started with a mouse
  DreamWorks Animation:
    template:
      name: Studio
      company: 521
      summary: >-
        DreamWorks Animation is an American animation studio that produces
        animated films and television programs and is a subsidiary of Universal
        Pictures.
  Hanna-Barbera:
    template:
      name: Studio
      company: 1353
      list: 'https://trakt.tv/users/goape/lists/hanna-barbera'
      summary: >-
        Hanna-Barbera Productions, Inc. also variously known as H-B Enterprises,
        H-B Production Co., and Hanna-Barbera Cartoons, Inc., was an American
        animation studio and production company founded in 1957 by Tom and Jerry
        creators and former Metro-Goldwyn-Mayer animation directors William
        Hanna and Joseph Barbera and dominated television with a variety of
        animated series, including The Huckleberry Hound Show, The Flintstones,
        The Yogi Bear Show, The Jetsons, Wacky Races, Scooby-Doo, Where Are You!
        and The Smurfs
  Pixar Animation Studios:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/pixar-animation-studios'
      summary: >-
        Pixar Animation Studios is an American computer animation studio known
        for its critically and commercially successful feature films. It is
        based in Emeryville, California, and is a subsidiary of Walt Disney
        Studios owned by The Walt Disney Company.
  Pixar Short Films:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/pixar-shorts'
      summary: >-
        Beginning with Pixar's second film A Bug's Life, almost all subsequent
        Pixar feature films have been shown in theaters along with a
        Pixar-created original short film, known as a "short." Other Pixar
        shorts, released only on home media, were created to showcase Pixar's
        technology or cinematic capabilities, or on commission for clients.
    collection_mode: hide_items
  Studio Ghibli Animation:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/studio-ghibli'
      summary: >-
        Studio Ghibli Inc. is a Japanese animation film studio headquartered in
        Koganei, Tokyo. The studio is best known for its animated feature films,
        and has also produced several short films, television commercials, and
        one television film. The studio’s mascot and most recognizable symbol is
        the character, Totoro, a giant cat-like spirit from the 1988 classic, My
        Neighbor Totoro.
  Walt Disney Animation Studios:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/walt-disney-animation-studios'
      summary: >-
        Walt Disney Animation Studios (WDAS), sometimes shortened to Disney
        Animation, is an American animation studio that creates animated
        features and short films for The Walt Disney Company. Founded on October
        16, 1923 by brothers Walt Disney and Roy O. Disney, it is one of the
        oldest-running animation studios in the world. It is currently organized
        as a division of Walt Disney Studios and is headquartered at the Roy E.
        Disney Animation Building at the Walt Disney Studios lot in Burbank,
        California.
