templates:
  Studio:
    optional:
      - list
      - summary
    tmdb_company: <<company>>
    trakt_list: <<list>>
    smart_label: release.asc
    sort_title: '!5_Studio <<collection_name>>'
    summary: <<summary>>
  'Studio [Sort Title]':
    optional:
      - list
      - summary
    tmdb_company: <<company>>
    trakt_list: <<list>>
    smart_label: release.asc
    sort_title: '!5_Studio <<sort_title>>'
    summary: <<summary>>
  Studio - Smart:
    optional:
      - summary
    smart_filter:
      any:
        studio: <<studio>>
        title: <<title>>
      sort_by: release.asc
    item_label: <<collection_name>>
    sort_title: '!5_Studio <<collection_name>>'
    summary: <<summary>>
  'Studio [Sort Title] - Smart':
    optional:
      - summary
    smart_filter:
      any:
        studio: <<studio>>
        title: <<title>>
      sort_by: release.asc
    item_label: <<collection_name>>
    sort_title: '!5_Studio <<sort_title>>'
    summary: <<summary>>
  Studio - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    smart_label: release.asc
    sort_title: '!5_Studio <<collection_name>>'
    summary: <<summary>>
  'Studio [Sort Title] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    smart_label: release.asc
    sort_title: '!5_Studio <<sort_title>>'
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: show_items
    sort_title: '!5_Studio <<collection_name>>'
    summary: <<summary>>
  'Studio [Sort Title] - Trakt List Custom Order':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: show_items
    sort_title: '!5_Studio <<sort_title>>'
    summary: <<summary>>
  Studio - Search:
    optional:
      - summary
    plex_search:
      title: <<title>>
    smart_label: release.asc
    sort_title: '!5_Studio <<collection_name>>'
    summary: <<summary>>
collections:
  Disney:
    template:
      name: Studio - Trakt List
      list: disney-25927893
      summary: It was all started with a mouse
  Disneynature:
    template:
      name: Studio
      company: 4436
      summary: >-
        Disneynature is an independent film studio that specializes in the
        production of nature documentary films for The Walt Disney Studios. The
        production company was founded on April 21, 2008, and is headquartered
        in Paris, France.
  DCEU:
    template:
      name: Studio - Trakt List
      list: dceu
      summary: >-
        The DC Extended Universe is an American media franchise and shared
        universe centered on a series of superhero films based on characters
        that appear in American comic books by DC Comics, produced by DC Films
        and distributed by Warner Bros. Pictures.
  Rankin/Bass Christmas Classics:
    template:
      name: Studio - Trakt List
      list: rankin-bass-christmas-classics
      summary: >-
        Rankin/Bass Animated Entertainment (founded and formerly known as
        Videocraft International, Ltd. and Rankin/Bass Productions, Inc.) was an
        American production company known for its seasonal television specials,
        usually done in stop motion animation. Rankin/Bass' stop-motion
        productions are recognizable by their visual style of doll-like
        characters with spheroid body parts and ubiquitous powdery snow using an
        animation technique called "Animagic". Often, traditional cel animation
        scenes of falling snow would be projected over the action to create the
        effect of a snowfall.
    name_mapping: RankinBass Christmas Classics
  Marvel Cinematic Universe:
    template:
      name: Studio - Trakt List Custom Order
      list: marvel-cinematic-universe-timeline
      summary: >-
        The Marvel Cinematic Universe is a media franchise created by Marvel
        Studios, set primarily in a shared universe designated as the reality
        Earth-199999 within Marvel's multiverse system, with some installments
        also set in adjacent or branching realities.

        Starting with Iron Man, the franchise is comprised mainly of films
        independently made by Marvel Studios, that are primarily set within this
        same universe, much like Marvel has done with their comics.
  National Geographic:
    template:
      name: Studio - Trakt List
      list: national-geographic
      summary: >-
        National Geographic is an American pay television network and flagship
        channel owned by National Geographic Partners, a joint venture between
        The Walt Disney Company and the National Geographic Society, with the
        operational management handled by Walt Disney Television.
  Universal Monsters:
    template:
      name: Studio - Trakt List
      list: universal-monsters
      summary: >-
        Universal Monsters is a media franchise based on a series of horror
        films primarily produced by Universal Pictures from the 1930s to the
        1950s.
