templates:
  Studio:
    default:
      sort_title: '!5_Studio <<collection_name>>'
    optional:
      - list
      - sort_title
      - summary
    tmdb_company: <<company>>
    trakt_list: <<list>>
    smart_label: release.asc
    sort_title: '!5_<<sort_title>>'
    summary: <<summary>>
  Studio - Smart:
    default:
      sort_title: '!5_Studio <<collection_name>>'
    optional:
      - sort_title
      - summary
    smart_filter:
      any:
        studio: <<studio>>
        title: <<title>>
      sort_by: release.asc
    item_label: <<collection_name>>
    sort_title: '!5_<<sort_title>>'
    summary: <<summary>>
  Studio - Trakt List:
    default:
      sort_title: '!5_Studio <<collection_name>>'
    optional:
      - sort_title
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    smart_label: release.asc
    sort_title: '!5_<<sort_title>>'
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    default:
      sort_title: '!5_Studio <<collection_name>>'
    optional:
      - sort_title
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: show_items
    sort_title: '!5_<<sort_title>>'
    summary: <<summary>>
  Studio - Search:
    default:
      sort_title: '!5_Studio <<collection_name>>'
    optional:
      - sort_title
      - summary
    plex_search:
      title: <<title>>
    smart_label: release.asc
    sort_title: '!5_<<sort_title>>'
    summary: <<summary>>
collections:
  Disney:
    template:
      name: Studio
      company: '2, 3, 6125, 3166'
      list: disney-25927893
      summary: It was all started with a mouse
  Disneynature:
    template:
      name: Studio
      company: 4436
      summary: >-
        Disneynature is an independent film studio that specializes in the
        production of nature documentary films for The Walt Disney Studios. The
        production company was founded on April 21, 2008, and is headquartered
        in Paris, France.
  National Geographic:
    template:
      name: Studio - Trakt List
      list: national-geographic
      summary: >-
        National Geographic is an American pay television network and flagship
        channel owned by National Geographic Partners, a joint venture between
        The Walt Disney Company and the National Geographic Society, with the
        operational management handled by Walt Disney Television.
