templates:
  Studio:
    tmdb_company: <<company>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Smart:
    smart_filter:
      any:
        studio: <<studio>>
      sort_by: release.desc
    sort_title: ++_4<<collection_name>>
    only_run_on_create: true
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: custom
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    sync_mode: sync
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Disney:
    template:
      name: Studio
      company: '2, 3, 6125, 3166'
      list: disney
      summary: It was all started with a mouse
  DCEU:
    template:
      name: Studio - Trakt List
      list: dceu
      summary: >-
        The DC Extended Universe is an American media franchise and shared
        universe centered on a series of superhero films based on characters
        that appear in American comic books by DC Comics, produced by DC Films
        and distributed by Warner Bros. Pictures.
  Rankin/Bass Christmas Classics:
    template:
      name: Studio - Trakt List
      list: rankin-bass-christmas-classics
      summary: >-
        Rankin/Bass Animated Entertainment (founded and formerly known as
        Videocraft International, Ltd. and Rankin/Bass Productions, Inc.) was an
        American production company known for its seasonal television specials,
        usually done in stop motion animation. Rankin/Bass' stop-motion
        productions are recognizable by their visual style of doll-like
        characters with spheroid body parts and ubiquitous powdery snow using an
        animation technique called "Animagic". Often, traditional cel animation
        scenes of falling snow would be projected over the action to create the
        effect of a snowfall.
    name_mapping: RankinBass Christmas Classics
  Marvel Cinematic Universe:
    template:
      name: Studio - Trakt List Custom Order
      list: marvel-cinematic-universe-timeline
      summary: >-
        The Marvel Cinematic Universe is a media franchise created by Marvel
        Studios, set primarily in a shared universe designated as the reality
        Earth-199999 within Marvel's multiverse system, with some installments
        also set in adjacent or branching realities.

        Starting with Iron Man, the franchise is comprised mainly of films
        independently made by Marvel Studios, that are primarily set within this
        same universe, much like Marvel has done with their comics.
  Universal Monsters:
    template:
      name: Studios - Trakt List
      list: universal-monsters
      summary: >-
        Universal Monsters is a media franchise based on a series of horror
        films primarily produced by Universal Pictures from the 1930s to the
        1950s.
