templates:
  Studio:
    collection_order: release
    collection_mode: hide_items
    tmdb_company: <<company>>
    sort_title: ++_6<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  A24:
    template:
      name: Studio
      company: 41077
      list: a24
      summary: >-
        A24 is an American independent entertainment company founded on August
        20, 2012, by Daniel Katz, David Fenkel, and John Hodges that specializes
        in film and television production, as well as film distribution. It is
        based in New York City.
  DC:
    template:
      name: Studio
      company: 9993
      list: dc
      summary: >-
        DC Films is an American film studio that is a subsidiary of Warner Bros.
        through the Warner Bros. Pictures Group, dedicated to the production of
        films based on characters from DC Entertainment.
  DC Animated Originals:
    template:
      name: Studio - Trakt List
      list: dc-animated
      summary: >-
        The DC Animated Universe (DCAU; also referred to as the Timmverse or
        Diniverse by fans) is a shared universe of superhero-based animated
        television series, produced by Warner Bros. Animation and based on
        characters that appear in American comic books published by DC Comics.
  Disney:
    template:
      name: Studio
      company: '2, 3, 6125, 3166'
      list: disney
      summary: It was all started with a mouse
  Marvel:
    template:
      name: Studio
      company: '7505, 19551, 420, 11106, 13252, 38679'
      list: marvel
      summary: With great power comes great responsibility
  Marvel Animation:
    template:
      name: Studio
      company: 13252
      summary: >-
        Marvel Animation, Inc. (originally the home entertainment and TV
        production division of Marvel Studios and also referred to as Marvel
        Family Entertainment) is an American animation production company. The
        Marvel Studios subsidiary was incorporated on January 25, 2008 to direct
        Marvel's efforts in animation and home entertainment markets. The
        incorporated Marvel Animation included then ongoing animation efforts by
        Marvel Studios with Lionsgate and Nickelodeon. Marvel Animation operated
        under Marvel Studios, a subsidiary of Walt Disney Studios, a division of
        The Walt Disney Company.
    plex_search:
      title: I Am Groot
  Nickelodeon:
    template:
      name: Studio - Trakt List
      list: nickelodeon-movies
      summary: 'Nick, Nick, Nick, Nick, Ni-, Nick, Nick, Nick Nickelodeon'
    tmdb_movie: 439059
    sync_to_trakt_list: nickelodeon
  Sony Pictures Animation:
    template:
      name: Studio
      company: 2251
      summary: >-
        Sony Pictures Animation Inc. is an American animation studio owned by
        Sony Entertainment's Sony Pictures Entertainment through their Motion
        Picture Group division and founded on May 9, 2002.
