templates:
  Studio:
    tmdb_company: <<company>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Smart:
    smart_filter:
      any:
        studio: <<studio>>
      sort_by: release.desc
    sort_title: ++_4<<collection_name>>
    only_run_on_create: true
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: custom
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    sync_mode: sync
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  A24:
    template:
      name: Studio
      company: 41077
      list: a24
      summary: >-
        A24 is an American independent entertainment company founded on August
        20, 2012, by Daniel Katz, David Fenkel, and John Hodges that specializes
        in film and television production, as well as film distribution. It is
        based in New York City.
  Disney:
    template:
      name: Studio + Network
      company: '2, 3, 6125, 3166, 3475, 670'
      network: '54, 281, 44, 142'
      list: disney
    plex_search:
      title:
        - The Wonderful World of Disney
        - Disneyland
    show_filtered: true
    filters:
      title.not: Storm of the Century
  Marvel Cinematic Universe:
    template:
      name: Studio - Trakt List
      list: mcu
      summary: >-
        The Marvel Cinematic Universe is a media franchise created by Marvel
        Studios, set primarily in a shared universe designated as the reality
        Earth-199999 within Marvel's multiverse system, with some installments
        also set in adjacent or branching realities.

        Starting with Iron Man, the franchise is comprised mainly of films
        independently made by Marvel Studios, that are primarily set within this
        same universe, much like Marvel has done with their comics.
