templates:
  Studio:
    tmdb_company: <<company>>
    collection_order: release
    collection_mode: hide_items
    default:
      sort_title: ++_6<<collection_name>>
    optional:
      - list
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    default:
      sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    collection_order: release
    collection_mode: hide_items
    default:
      sort_title: ++_6<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Hanna-Barbera:
    template:
      name: Studio - Trakt List
      list: hanna-barbera
      summary: >-
        Hanna-Barbera Productions, Inc. also variously known as H-B Enterprises,
        H-B Production Co., and Hanna-Barbera Cartoons, Inc., was an American
        animation studio and production company founded in 1957 by Tom and Jerry
        creators and former Metro-Goldwyn-Mayer animation directors William
        Hanna and Joseph Barbera and dominated television with a variety of
        animated series, including The Huckleberry Hound Show, The Flintstones,
        The Yogi Bear Show, The Jetsons, Wacky Races, Scooby-Doo, Where Are You!
        and The Smurfs
  Marvel Filtered:
    template:
      name: Studio
      company: '7505, 19551, 420, 11106, 13252, 38679'
      list: marvel
      summary: With great power comes great responsibility
    plex_search:
      title: I Am Groot
    show_filtered: true
    filters:
      title.not: 'Men In Black: The Series'
    name: Marvel
  Pixar Animation Studios:
    template:
      name: Studio - Trakt List
      list: pixar-animation-studios
      summary: >-
        Pixar Animation Studios is an American computer animation studio known
        for its critically and commercially successful feature films. It is
        based in Emeryville, California, and is a subsidiary of Walt Disney
        Studios owned by The Walt Disney Company.
    plex_search:
      title: Pixar
