templates:
  Studio:
    tmdb_company: <<company>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - list
      - summary
    trakt_list: <<list>>
    summary: <<summary>>
  Studio - Smart:
    smart_filter:
      any:
        studio: <<studio>>
      sort_by: release.desc
    sort_title: ++_4<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List:
    trakt_list: <<list>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
  Studio - Trakt List Custom Order:
    trakt_list: <<list>>
    collection_order: custom
    collection_mode: show_items
    sort_title: ++_4<<collection_name>>
    sync_mode: sync
    optional:
      - summary
    summary: <<summary>>
  Studio - Search:
    plex_search:
      title: <<title>>
    sort_title: ++_4<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
collections:
  A24:
    template:
      name: Studio
      company: 41077
      list: 'https://trakt.tv/users/goape/lists/a24'
      summary: >-
        A24 is an American independent entertainment company founded on August
        20, 2012, by Daniel Katz, David Fenkel, and John Hodges that specializes
        in film and television production, as well as film distribution. It is
        based in New York City.
  DC:
    template:
      name: Studio
      company: 9993
      list: 'https://trakt.tv/users/goape/lists/dc'
      summary: >-
        DC Films is an American film studio that is a subsidiary of Warner Bros.
        through the Warner Bros. Pictures Group, dedicated to the production of
        films based on characters from DC Entertainment.
  DC Animated Originals:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/dc-animated'
      summary: >-
        The DC Animated Universe (DCAU; also referred to as the Timmverse or
        Diniverse by fans) is a shared universe of superhero-based animated
        television series, produced by Warner Bros. Animation and based on
        characters that appear in American comic books published by DC Comics.
  Disney:
    template:
      name: Studio
      company: '2, 3, 6125, 3166, 3475, 670'
      list: disney
    plex_search:
      title:
        - The Wonderful World of Disney
        - Disneyland
    show_filtered: true
    filters:
      title.not: Storm of the Century
  LEGO:
    template:
      name: Studio - Search
      title: 'LEGO, Lego'
      summary: The bane of your foot's existence.
  Marvel Cinematic Universe:
    template:
      name: Studio - Trakt List
      list: 'https://trakt.tv/users/goape/lists/mcu'
      summary: >-
        The Marvel Cinematic Universe is a media franchise created by Marvel
        Studios, set primarily in a shared universe designated as the reality
        Earth-199999 within Marvel's multiverse system, with some installments
        also set in adjacent or branching realities.

        Starting with Iron Man, the franchise is comprised mainly of films
        independently made by Marvel Studios, that are primarily set within this
        same universe, much like Marvel has done with their comics.
