templates:
  Decade:
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade <<mapping_name>>'
    summary: <<summary>>
  'Decade [2000s]':
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade~ <<mapping_name>>'
    summary: <<summary>>
collections:
  2000s:
    template:
      name: 'Decade [2000s]'
      name_mapping: '2000s [TV Shows - Kids]'
      year:
        - 2000
        - 2001
        - 2002
        - 2003
        - 2004
        - 2005
        - 2006
        - 2007
        - 2008
        - 2009
      summary: TV shows released from 2000-2009
  1990s:
    template:
      name: Decade
      name_mapping: '1990s [TV Shows - Kids]'
      year:
        - 1990
        - 1991
        - 1992
        - 1993
        - 1994
        - 1995
        - 1996
        - 1997
        - 1998
        - 1999
      summary: TV Shows released from 1990-1999
  1980s:
    template:
      name: Decade
      name_mapping: '1980s [TV Shows - Kids]'
      year:
        - 1980
        - 1981
        - 1982
        - 1983
        - 1984
        - 1985
        - 1986
        - 1987
        - 1988
        - 1989
      summary: TV Shows released from 1980-1989
  1970s:
    template:
      name: Decade
      name_mapping: '1970s [TV Shows - Kids]'
      year:
        - 1970
        - 1971
        - 1972
        - 1973
        - 1974
        - 1975
        - 1976
        - 1977
        - 1978
        - 1979
      summary: TV Shows released from 1970-1979
  1960s:
    template:
      name: Decade
      name_mapping: '1960s [TV Shows - Kids]'
      year:
        - 1960
        - 1961
        - 1962
        - 1963
        - 1964
        - 1965
        - 1966
        - 1967
        - 1968
        - 1969
      summary: TV Shows released from 1960-1969
  1950s:
    template:
      name: Decade
      name_mapping: '1950s [TV Shows - Kids]'
      year:
        - 1950
        - 1951
        - 1952
        - 1953
        - 1954
        - 1955
        - 1956
        - 1957
        - 1958
        - 1959
      summary: TV Shows released from 1950-1959
