templates:
  Decade:
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade <<mapping_name>>'
    summary: <<summary>>
  'Decade [2000s]':
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade~ <<mapping_name>>'
    summary: <<summary>>
collections:
  'Decades: 2000s':
    template:
      name: 'Decade [2000s]'
      year:
        - 2000
        - 2001
        - 2002
        - 2003
        - 2004
        - 2005
        - 2006
        - 2007
        - 2008
        - 2009
      summary: >-
        Sweet! The 2000s bring a thrilling mix of films, featuring Harry Potter
        and the Sorcerer’s Stone and the epic Gladiator. This collection
        captures the innovation and magic that defined a memorable decade in
        cinema!
  'Decades: 1990s':
    template:
      name: Decade
      year:
        - 1990
        - 1991
        - 1992
        - 1993
        - 1994
        - 1995
        - 1996
        - 1997
        - 1998
        - 1999
      summary: >-
        All that and a bag of chips! The Nifty Nineties showcase a variety of
        films, including Titanic and Jurassic Park, that captivated audiences
        around the globe. This collection highlights the creativity and
        diversity of a decade that left a lasting impact on cinema!
  'Decades: 1980s':
    template:
      name: Decade
      year:
        - 1980
        - 1981
        - 1982
        - 1983
        - 1984
        - 1985
        - 1986
        - 1987
        - 1988
        - 1989
      summary: >-
        Totally awesome! The tubular Eighties are packed with iconic flicks like
        The Breakfast Club and Back to the Future, capturing the spirit of a
        generation. Get ready for a mix of adventure, comedy, and unforgettable
        characters!
  'Decades: 1970s':
    template:
      name: Decade
      year:
        - 1970
        - 1971
        - 1972
        - 1973
        - 1974
        - 1975
        - 1976
        - 1977
        - 1978
        - 1979
      summary: >-
        Far out! The funky Seventies deliver bold films, from the gritty realism
        of Taxi Driver to the fantastical adventure of Star Wars. This decade
        was all about pushing boundaries and exploring new cinematic
        territories!
  'Decades: 1960s':
    template:
      name: Decade
      year:
        - 1960
        - 1961
        - 1962
        - 1963
        - 1964
        - 1965
        - 1966
        - 1967
        - 1968
        - 1969
      summary: >-
        Groovy, baby! The Swinging Sixties feature iconic films like The
        Graduate and Psycho, highlighting the bold storytelling and innovation
        of the time. This collection celebrates the creativity that made the
        decade unforgettable!
  'Decades: 1950s':
    template:
      name: Decade
      year:
        - 1950
        - 1951
        - 1952
        - 1953
        - 1954
        - 1955
        - 1956
        - 1957
        - 1958
        - 1959
      summary: >-
        Well, I’ll be! The sensational Fifties shine with a mix of iconic films
        like Rebel Without a Cause and the thrilling North by Northwest. This
        collection captures the charm and excitement of a decade filled with
        unforgettable stories!
  'Decades: 1940s':
    template:
      name: Decade
      year:
        - 1940
        - 1941
        - 1942
        - 1943
        - 1944
        - 1945
        - 1946
        - 1947
        - 1948
        - 1949
      summary: >-
        Ain’t it a peach? The Fabulous Forties bring a mix of daring tales and
        unforgettable characters, featuring classics like Casablanca and It’s a
        Wonderful Life. This captivating collection captures the resilience and
        romance of the era in unforgettable films!
  'Decades: 1930s':
    template:
      name: Decade
      year:
        - 1930
        - 1931
        - 1932
        - 1933
        - 1934
        - 1935
        - 1936
        - 1937
        - 1938
        - 1939
      summary: >-
        Well, I’ll be! The 1930s ushered in the age of talkies, transforming the
        silver screen forever! This collection features films like Frankenstein
        and Snow White and the Seven Dwarfs, showcasing the magic of sound and
        storytelling that lifted spirits during tough times.
  'Decades: 1920s':
    template:
      name: Decade
      year:
        - 1920
        - 1921
        - 1922
        - 1923
        - 1924
        - 1925
        - 1926
        - 1927
        - 1928
        - 1929
      summary: >-
        Step right up to the Roaring Twenties, where glamour meets adventure!
        This collection features iconic flicks like The Jazz Singer and
        Metropolis, which set the stage for the future of cinema. Enjoy the
        dazzling performances and captivating stories that are the cat’s
        pajamas!
