templates:
  Decade:
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade <<mapping_name>>'
    summary: <<summary>>
collections:
  1990s:
    template:
      name: Decade
      year:
        - 1990
        - 1991
        - 1992
        - 1993
        - 1994
        - 1995
        - 1996
        - 1997
        - 1998
        - 1999
      summary: Movies released from 1990-1999
  1980s:
    template:
      name: Decade
      year:
        - 1980
        - 1981
        - 1982
        - 1983
        - 1984
        - 1985
        - 1986
        - 1987
        - 1988
        - 1989
      summary: Movies released from 1980-1989
  1970s:
    template:
      name: Decade
      year:
        - 1970
        - 1971
        - 1972
        - 1973
        - 1974
        - 1975
        - 1976
        - 1977
        - 1978
        - 1979
      summary: Movies released from 1970-1979
  1960s:
    template:
      name: Decade
      year:
        - 1960
        - 1961
        - 1962
        - 1963
        - 1964
        - 1965
        - 1966
        - 1967
        - 1968
        - 1969
      summary: Movies released from 1960-1969
