templates:
  Decade:
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade <<mapping_name>>'
    summary: <<summary>>
  'Decade [2000s]':
    optional:
      - summary
    smart_filter:
      any:
        year: <<year>>
      sort_by: year.asc
    sort_title: '!4_Decade~ <<mapping_name>>'
    summary: <<summary>>
collections:
  'Decades: 2000s':
    template:
      name: 'Decade [2000s]'
      year:
        - 2000
        - 2001
        - 2002
        - 2003
        - 2004
        - 2005
        - 2006
        - 2007
        - 2008
        - 2009
      summary: >-
        Dive into the dynamic 2000s, a decade that redefined cinema with bold
        storytelling and innovative technology! This collection features a
        diverse array of films, from thrilling blockbusters and heartwarming
        tales to groundbreaking animations and unforgettable romances. With a
        blend of fresh voices and classic franchises, these flicks capture the
        essence of a time when cinema truly came into its own. Get comfy and
        prepare to relive the magic of the 2000s!
  'Decades: 1990s':
    template:
      name: Decade
      year:
        - 1990
        - 1991
        - 1992
        - 1993
        - 1994
        - 1995
        - 1996
        - 1997
        - 1998
        - 1999
      summary: >-
        Enter the totally awesome nineties, a decade of groundbreaking films and
        unforgettable moments! This collection features a vibrant mix of classic
        comedies, epic adventures, and heartwarming dramas that defined the era.
        From the rise of animated masterpieces to the grunge-fueled stories of a
        generation, these flicks capture the spirit of a time when movies were
        as diverse and dynamic as the decade itself. So throw on your flannel
        and prepare for a nostalgia trip through the iconic films of the
        nineties!
  'Decades: 1980s':
    template:
      name: Decade
      year:
        - 1980
        - 1981
        - 1982
        - 1983
        - 1984
        - 1985
        - 1986
        - 1987
        - 1988
        - 1989
      summary: >-
        Welcome to the radical eighties, a decade bursting with neon colors, big
        hair, and unforgettable tunes! This collection is a nostalgic trip
        filled with iconic blockbusters, quirky comedies, and action-packed
        adventures that defined a generation. From heartwarming teen dramas to
        sci-fi thrillers, these films serve up all the charm and outrageous fun
        of the era. So grab your cassette tapes and relive the magic of the
        eighties!
  'Decades: 1970s':
    template:
      name: Decade
      year:
        - 1970
        - 1971
        - 1972
        - 1973
        - 1974
        - 1975
        - 1976
        - 1977
        - 1978
        - 1979
      summary: >-
        Travel back to the funky seventies, where counterculture collided with
        cinematic creativity! This collection features a thrilling mix of
        groundbreaking films, from gritty dramas and mind-bending sci-fi to rock
        'n' roll musicals and cult classics. With a soundtrack that still
        resonates and stories that pushed the envelope, these flicks capture the
        spirit of a decade defined by rebellion and innovation. Throw on your
        platform shoes and dive into a world of cinematic gold!
  'Decades: 1960s':
    template:
      name: Decade
      year:
        - 1960
        - 1961
        - 1962
        - 1963
        - 1964
        - 1965
        - 1966
        - 1967
        - 1968
        - 1969
      summary: >-
        Groove on over to the swinging sixties, a decade of vibrant vibes and
        cultural revolutions! This collection features a kaleidoscope of
        colorful films, from iconic musicals and revolutionary dramas to
        psychedelic adventures that captured the spirit of the era. With
        unforgettable tunes and bold storytelling, these flicks invite you to
        relive the excitement and experimentation of a truly transformative time
        in cinema. So, grab your bell bottoms and let's boogie down memory lane!
  'Decades: 1950s':
    template:
      name: Decade
      year:
        - 1950
        - 1951
        - 1952
        - 1953
        - 1954
        - 1955
        - 1956
        - 1957
        - 1958
        - 1959
      summary: >-
        Get ready to rock around the clock with the sensational fifties! This
        collection celebrates the decade of sock hops, greasers, and iconic
        blockbusters that defined a generation. From dazzling musicals to
        thrilling sci-fi adventures, these films are packed with the charm and
        flair of a bygone era. So grab your poodle skirt or leather jacket and
        dive into a world of unforgettable fun and classic storytelling!
  'Decades: 1940s':
    template:
      name: Decade
      year:
        - 1940
        - 1941
        - 1942
        - 1943
        - 1944
        - 1945
        - 1946
        - 1947
        - 1948
        - 1949
      summary: >-
        Enjoy the fabulous forties, a decade brimming with war-time courage and
        post-war romance! This collection features a captivating mix of film
        noir mysteries, dazzling musicals, and heartwarming tales that captured
        the spirit of resilience and hope. From the silver linings of love
        stories to the grit of wartime dramas, these flicks are sure to
        transport you back to a time of cinematic magic and unforgettable
        moments!
  'Decades: 1930s':
    template:
      name: Decade
      year:
        - 1930
        - 1931
        - 1932
        - 1933
        - 1934
        - 1935
        - 1936
        - 1937
        - 1938
        - 1939
      summary: >-
        Welcome to the era of silver screen dreams and golden age glamour! The
        1930s brought us unforgettable musicals, heartwarming dramas, and the
        rise of animated classics. This collection showcases the enchanting
        films that whisked audiences away from the Great Depression into a world
        of wonder and whimsy. So dim the lights and let the magic of the
        thirties take you on a delightful journey!
  'Decades: 1920s':
    template:
      name: Decade
      year:
        - 1920
        - 1921
        - 1922
        - 1923
        - 1924
        - 1925
        - 1926
        - 1927
        - 1928
        - 1929
      summary: >-
        Step back in time to the roaring twenties, where flappers danced, jazz
        filled the air, and silent films gave way to talkies! This delightful
        collection features the iconic flicks that defined an era of glamour and
        excitement. Grab your cloche hat and enjoy the cinematic gems that
        brought the jazz age to life!
