templates:
  Profiles - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide_items
    sort_title: ++_2<<collection_name>>
    optional:
      - label
      - summary
    label: <<label>>
    summary: <<summary>>
collections:
  Aaron:
    template:
      name: Profiles - Trakt List
      list:
        - movies-aaron
        - movies-aaron-kids
      label: Aaron
      summary: Movies for Aaron
