templates:
  Profiles - Trakt List:
    trakt_list: <<list>>
    sync_mode: sync
    sort_title: ++_1.6<<collection_name>>
    smart_label: title.asc
    optional:
      - label
      - summary
    label: <<label>>
    summary: <<summary>>
collections:
  Aaron:
    template:
      name: Profiles - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-aaron'
      label: Aaron
      summary: Movies for Aaron
