templates:
  Profiles - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
collections:
  Aaron:
    template:
      name: Profiles - Trakt List
      list: tv-aaron
    plex_search:
      title: Wet Hot American Summer
    user_rating: 10
    build_collection: false
