templates:
  Profiles - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide_items
    sort_title: ++_2<<collection_name>>
    optional:
      - label
      - summary
    label: <<label>>
    summary: <<summary>>
collections:
  Aaron:
    template:
      name: Profiles - Trakt List
      list: 'tv-aaron, tv-kids-aaron'
      label: Aaron
      summary: TV Shows for Aaron
    plex_search:
      title: Wet Hot American Summer
  Casey:
    template:
      name: Profiles - Trakt List
      list: tv-casey
      label: Casey
      summary: TV Shows for Casey
  Tom:
    template:
      name: Profiles - Trakt List
      list: tv-dad
      label: Tom
      summary: TV Shows for Tom
