templates:
  Profiles - Trakt List:
    trakt_list: <<list>>
    sync_mode: sync
    sort_title: '!2_Profile <<collection_name>>'
    smart_label: title.asc
    optional:
      - label
      - summary
    label: <<label>>
    summary: <<summary>>
collections:
  Aaron:
    template:
      name: Profiles - Trakt List
      list: movies-aaron
      summary: Movies for Aaron
