templates:
  Profiles - Trakt List:
    trakt_list: <<list>>
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide_items
    sort_title: ++_2<<collection_name>>
    optional:
      - label
      - summary
    label: <<label>>
    summary: <<summary>>
collections:
  Aaron:
    template:
      name: Profiles - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-aaron'
      label: Aaron
      summary: Movies for Aaron
  Grandpa:
    smart_filter:
      all:
        label: Grandpa
    sort_title: ~~_CGrandpa
    summary: Movies for Grandpa
