templates:
  First - Custom:
    optional:
      - sort_title
      - summary
    sort_title: '!_First <<collection_name>>'
    summary: <<summary>>
  'First [Sort Title] - Custom':
    optional:
      - list
      - name_mapping
      - sort_title
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    name_mapping: <<name_mapping>>
    sort_title: '!_First <<sort_title>>'
    summary: <<summary>>
collections:
  All-Time Faves:
    template:
      name: 'First [Sort Title] - Custom'
      sort_title: '!5All-Time Faves'
      summary: >-
        The champions of rewatchability. These tried-and-true favorites prove
        their worth with every viewing, offering the rare combination of comfort
        and quality that keeps you coming back.
    builder_level: episode
    collection_filtering: user
    smart_filter:
      sort_by: title.asc
      any:
        all:
          user_rating.gte: 9.5
        any:
          label: Aaron
  New Arrivals:
    template:
      name: 'First [Sort Title] - Custom'
      sort_title: '!1New Arrivals'
      name_mapping: 'New Arrivals [Music Videos]'
      summary: Fresh clips have landed!
    builder_level: episode
    smart_filter:
      all:
        added: 30
      limit: 100
      sort_by: added.desc
