templates:
  First - Custom:
    optional:
      - sort_title
      - summary
    sort_title: '!1_First <<collection_name>>'
    summary: <<summary>>
  'First [Sort Title] - Custom':
    optional:
      - sort_title
      - summary
    sort_title: '!1_First <<sort_title>>'
    summary: <<summary>>
collections:
  Favorites:
    collection_filtering: user
    plex_search:
      all:
        user_rating.gte: 4.5
      sort_by: title.desc
    summary: My Favorites
  Recently Added:
    template:
      name: 'First [Sort Title] - Custom'
      sort_title: '!Recently Added'
      summary: Added in the last 30 days
    smart_filter:
      all:
        added: 30
      limit: 100
      sort_by: added.desc
  Trending:
    template:
      name: First - Custom
      summary: Movies trending across the internet
    trakt_chart:
      chart: trending
      limit: 30
    smart_label: random
    sync_mode: sync
