templates:
  First - Custom:
    optional:
      - sort_title
      - summary
    sort_title: '!1_First <<collection_name>>'
    summary: <<summary>>
  'First [Sort Title] - Custom':
    optional:
      - sort_title
      - summary
    sort_title: '!1_First <<sort_title>>'
    summary: <<summary>>
collections: null
