Profiles - Trakt List:
  trakt_list: <<list>>
  sync_mode: sync
  collection_order: alpha
  collection_mode: hide_items
  sort_title: ++_1.6<<collection_name>>
  optional:
    - label
    - summary
  label: <<label>>
  summary: <<summary>>
