templates:
  Genre:
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    optional:
      - summary
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  Genre - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: release.asc
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Holiday] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: title.asc
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  Genre - Trakt List Episodes:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: alpha
    collection_level: episode
collections:
  Action:
    template:
      name: 'Genre [Bottom]'
      genre: Action
  Adventure:
    template:
      name: 'Genre [Bottom]'
      genre: Adventure
  Christmas:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-christmas
      smart_label: title.asc
      summary: Merry Christmas! Sh*tter was full.
  Comedy:
    template:
      name: 'Genre [Bottom]'
      genre: Comedy
  Crime:
    template:
      name: 'Genre [Bottom]'
      genre: Crime
  Fantasy:
    template:
      name: 'Genre [Bottom]'
      genre: Fantasy
  Halloween:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-halloween
      summary: '“Oh, look. Another glorious morning. Makes me sick!”'
  Music:
    template:
      name: Genre - Trakt List
      list: music
      item_genre: Music
      summary: "\U0001F3B8 \U0001F3B8 \U0001F3B8"
    smart_label: title.asc
  Musical:
    template:
      name: Genre - Trakt List
      list: movies-musicals
      summary: Does anyone still wear a hat?
  Mystery:
    template:
      name: 'Genre [Bottom]'
      genre: Mystery
  Sci-Fi:
    template:
      name: 'Genre [Bottom]'
      genre: Sci-Fi
      summary: 'Luke, I am your father'
  Sports:
    template:
      name: Genre
      genre: Sports
      list: movies-sports
      summary: PLAY BALL!
    smart_label: title.asc
  Stand Up:
    template:
      name: Genre - Trakt List
      list: movies-standup
    smart_label: title.asc
  Thanksgiving:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-thanksgiving
      summary: 'Gobble, gobble'
  Thriller:
    template:
      name: 'Genre [Bottom]'
      genre: Thriller
  Western:
    template:
      name: 'Genre [Bottom]'
      genre: Western
