templates:
  Genre:
    default:
      item_genre: <<collection_name>>
      item_label: Genre_<<collection_name>>
      label: Genre_<<collection_name>>
      sort_title: '!3_Genre <<collection_name>>'
    optional:
      - item_genre
      - item_label
      - label
      - sort_title
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    item_genre: Genre_<<item_genre>>
    item_label: Genre_<<item_label>>
    label: Genre_<<label>>
    sort_title: '!3_Genre <<sort_title>>'
    summary: <<summary>>
  'Genre [Bottom]':
    default:
      item_genre: <<collection_name>>
      item_label: Genre_<<collection_name>>
      label: Genre_<<collection_name>>
      sort_title: '!3_Genre <<collection_name>>'
    optional:
      - item_genre
      - item_label
      - label
      - sort_title
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    item_genre: Genre_<<item_genre>>
    item_label: Genre_<<item_label>>
    label: Genre_<<label>>
    sort_title: ~_Genre <<sort_title>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    default:
      item_genre: <<collection_name>>
      item_label: Genre_<<collection_name>>
      label: Genre_<<collection_name>>
      sort_title: ~_Genre <<collection_name>>
    optional:
      - item_genre
      - item_label
      - label
      - sort_title
      - summary
    item_genre: Genre_<<item_genre>>
    item_label: Genre_<<item_label>>
    label: Genre_<<label>>
    sort_title: ~_Genre <<sort_title>>
    summary: <<summary>>
  Genre - Trakt List:
    default:
      item_genre: <<collection_name>>
      item_label: Genre_<<collection_name>>
      label: Genre_<<collection_name>>
      smart_label: release.asc
      sort_title: '!3_Genre <<collection_name>>'
    optional:
      - item_genre
      - item_label
      - label
      - smart_label
      - sort_title
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: <<smart_label>>
    item_genre: <<item_genre>>
    item_label: Genre_<<item_label>>
    label: Genre_<<label>>
    sort_title: '!3_Genre <<sort_title>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    default:
      item_genre: <<collection_name>>
      item_label: Genre_<<collection_name>>
      label: Genre_<<collection_name>>
      sort_title: ~_Genre <<collection_name>>
      smart_label: release.asc
    optional:
      - item_genre
      - item_label
      - label
      - smart_label
      - sort_title
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: <<smart_label>>
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    label: <<label>>
    sort_title: ~_Genre <<sort_title>>
    summary: <<summary>>
  Genre - Trakt List Episodes:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: alpha
    collection_level: episode
collections:
  Action:
    template:
      name: 'Genre [Bottom]'
      genre: Action
  Adventure:
    template:
      name: 'Genre [Bottom]'
      genre: Adventure
  Christmas:
    template:
      name: Genre - Trakt List
      list: movies-christmas
      smart_label: title.asc
      sort_title: ~Christmas
      summary: Merry Christmas! Sh*tter was full.
  Comedy:
    template:
      name: 'Genre [Bottom]'
      genre: Comedy
  Crime:
    template:
      name: 'Genre [Bottom]'
      genre: Crime
  Fantasy:
    template:
      name: 'Genre [Bottom]'
      genre: Fantasy
  Halloween:
    template:
      name: Genre - Trakt List
      list: movies-halloween
      smart_label: title.asc
      sort_title: ~Halloween
      summary: '“Oh, look. Another glorious morning. Makes me sick!”'
  Music:
    template:
      name: Genre - Trakt List
      list: music
      item_genre: Music
      smart_label: title.asc
      summary: "\U0001F3B8 \U0001F3B8 \U0001F3B8"
  Musical:
    template:
      name: Genre - Trakt List
      list: movies-musicals
      item_genre: Musical
      summary: Does anyone still wear a hat?
  Mystery:
    template:
      name: 'Genre [Bottom]'
      genre: Mystery
  Sci-Fi:
    template:
      name: 'Genre [Bottom]'
      genre: Sci-Fi
      summary: 'Luke, I am your father'
  Sports:
    template:
      name: Genre
      genre: Sports
      list: movies-sports
      item_genre: Sports
      smart_label: title.asc
      summary: PLAY BALL!
  Stand Up:
    template:
      name: Genre - Trakt List
      list: movies-standup
      item_genre: Stand-Up
      smart_label: title.asc
  Thanksgiving:
    template:
      name: Genre - Trakt List
      list: movies-thanksgiving
      item_genre: Thanksgiving
      smart_label: title.asc
      sort_title: ~Thanksgiving
      summary: 'Gobble, gobble'
  Thriller:
    template:
      name: 'Genre [Bottom]'
      genre: Thriller
  Western:
    template:
      name: 'Genre [Bottom]'
      genre: Western
