templates:
  Genre:
    smart_filter:
      all:
        genre: <<genre>>
        genre.not: Stand-Up
      sort_by: random
    sort_title: ~_<<collection_name>>
    only_run_on_create: true
    optional:
      - collection_order
      - item_genre
      - item_label
      - summary
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    summary: <<summary>>
  Genre - Trakt List:
    trakt_list: <<list>>
    sync_mode: sync
    sort_title: ~_<<collection_name>>
    optional:
      - item_genre
      - item_label
      - label
      - summary
    smart_label: release.asc
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    label: <<label>>
    summary: <<summary>>
collections:
  Christmas Horror:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-horror-christmas'
      item_genre: Christmas Horror
      name_mapping: Christmas Horror
      summary: Garbage Day!
    sort_title: ++_4.4Christmas Horror
    smart_label: title.asc
  Halloween:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-halloween'
      item_genre: Halloween
      summary: '“One, Two, Freddy''s Coming For You”'
    sort_title: ++_4.4Halloween
    smart_label: title.asc
  Horror:
    smart_filter:
      all:
        title.not: Gamboozle
      sort_by: random
    sort_title: ~_Horror
  Musical:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-musicals'
      item_genre: Musical
      name_mapping: Musical Horror
      summary: Creature of the night!
    sort_title: ++_4.5Musical
    smart_label: title.asc
