templates:
  Genre:
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    optional:
      - summary
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  Genre - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: release.asc
    item_genre: <<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Holiday] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: title.asc
    item_genre: <<collection_name>>
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List [Hide Items]':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: hide_items
    item_genre: <<collection_name>>
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List Episodes':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: custom
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
collections:
  Tinsel Time:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-christmas
      summary: >-
        It might be a bit chilly in here, but don't worry—these festive
        documentaries pack all the holiday spirit you need! With a sprinkle of
        cheer and a dash of history, these documentaries are a cozy way to warm
        up your Christmas spirit, even if there aren't many to choose from!
