templates:
  Genre:
    smart_filter:
      all:
        genre: <<genre>>
        genre.not: Stand-Up
      sort_by: random
    sort_title: ~_<<collection_name>>
    only_run_on_create: true
    optional:
      - collection_order
      - item_genre
      - item_label
      - summary
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    summary: <<summary>>
  Genre - Trakt List:
    trakt_list: <<list>>
    sync_mode: sync
    sort_title: ~_<<collection_name>>
    optional:
      - item_genre
      - item_label
      - label
      - summary
    smart_label: release.desc
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    label: <<label>>
    summary: <<summary>>
collections:
  Christmas:
    template:
      name: Genre - Trakt List
      list:
        - 'https://trakt.tv/users/goape/lists/movies-hallmark-christmas'
        - 'https://trakt.tv/users/goape/lists/movies-lifetime-christmas'
        - 'https://trakt.tv/users/goape/lists/movies-mom-christmas'
      summary: Merry Christmas!
  Hallmark Christmas:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-hallmark-christmas'
      summary: Merry Christmas!
