templates:
  Genre:
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    optional:
      - summary
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  Genre - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: release.asc
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Holiday] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: title.asc
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  Genre - Trakt List Episodes:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: alpha
    collection_level: episode
collections:
  Christmas Horror:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-horror-christmas
      summary: Garbage Day!
  Halloween:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-halloween
      summary: '“One, Two, Freddy''s Coming For You”'
  Horror:
    template:
      name: 'Genre [Bottom] - Custom'
    smart_filter:
      all:
        title.not: Gamboozle
        sort_by: random
  Musical:
    template:
      name: Genre - Trakt List
      list: movies-musicals
      name_mapping: Musical Horror
      summary: Creature of the night!
