templates:
  Genre:
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    optional:
      - summary
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  Genre - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: release.asc
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  Genre - Trakt List Other:
    optional:
      - summary
    trakt_list: <<list>>
    sync_mode: sync
    smart_label: release.asc
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Holiday] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: title.asc
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List [Hide Items]':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: hide_items
    item_genre: <<collection_name>>
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List Episodes':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: custom
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
collections:
  Adventure Seekers:
    template:
      name: Genre
      genre: Adventure
      summary: >-
        Embark on daring expeditions that blur the lines between treasure
        hunting and survival! Whether facing ancient curses, high-tech villains,
        or nature's deadliest forces, these genre-bending quests prove that
        adventure comes in many flavors - and all of them are dangerous.
  Clue Me In:
    template:
      name: Genre
      genre: Mystery
      summary: >-
        Whodunnit? Get ready for a ride full of twists, turns, and sleuthing
        galore. These mystery films will have you on the edge of your seat,
        piecing together clues and unraveling the truth before the final reveal.
  Criminal Intent:
    template:
      name: Genre
      genre: Crime
      summary: >-
        Get ready for gritty heists, dirty deals, and criminals with nothing to
        lose. These films dive deep into the underworld, where the stakes are
        high, and the law is nowhere to be found.
  Full Throttle:
    template:
      name: Genre
      genre: Action
      summary: >-
        Crank up the chaos with this arsenal of pedal-to-metal mayhem! From
        brass-knuckle brawls to missile-launching muscle cars, these films
        deliver pure, uncut adrenaline straight to the heart. Just remember - in
        this game, you shoot first and ask questions... never.
  Game Changers:
    template:
      name: Genre
      genre: Sports
      list: movies-sports
      summary: >-
        These films span all facets of sports, from heart-pounding drama to
        hilarious comedies and true stories of athletes who made their mark.
  Laugh Out Loud:
    template:
      name: Genre
      genre: Comedy
      summary: >-
        Get ready to laugh! These comedies are filled with wild humor,
        over-the-top characters, and unforgettable moments that’ll leave you
        grinning from ear to ear.
  Magic & Myth:
    template:
      name: Genre
      genre: Fantasy
      summary: >-
        Step into a world where magic is real and myths come alive. These films
        transport you to realms filled with legendary creatures, enchanted
        lands, and epic quests.
  Noir or Never:
    template:
      name: Genre - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/film-noir-movies'
      summary: >-
        Welcome to the wrong side of midnight, where cigarette smoke dances with
        danger and everyone's got an angle. These black-and-white beauties serve
        up hard-boiled detectives, dangerous dames, and enough double-crosses to
        make your head spin. Just remember - in this city, trust is the
        deadliest weapon of all.
  Out of This World:
    template:
      name: Genre
      genre: Science Fiction
      summary: >-
        Blast off to worlds beyond! These far-out flicks are packed with cosmic
        capers and mind-bending adventures that’ll take you light-years away.
        Enjoy sci-fi thrills and otherworldly chills for those craving the
        unknown!
  Plunder & Peril:
    template:
      name: Genre - Trakt List
      list: plunder-peril
      summary: >-
        Hoist the black flag for a treasure trove of maritime mayhem! From
        swashbuckling adventures to deadly sea battles, these salty tales
        showcase the ultimate ocean outlaws in action. Just remember - dead men
        tell no tales.
  Portrait Gallery:
    template:
      name: Genre - Trakt List
      list: portrait-gallery
      smart_label: title.desc
      summary: >-
        From humble beginnings to legendary status, these intimate portraits
        capture the rise, fall, and resurrection of cultural icons. Watch raw
        talent transform into stardom as ordinary people become extraordinary
        legends. Every breakthrough, breakdown, and comeback crafted these
        unforgettable legacies.
  Season's Greetings:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: season-s-greetings
      smart_label: title.asc
      summary: >-
        Break out the eggnog and mistletoe! These festive flicks are packed with
        holiday cheer and enough yuletide magic to make even Scrooge smile. It’s
        a holly jolly celebration of the season!
  Showstoppers:
    template:
      name: Genre - Trakt List
      list: showstoppers
      summary: >-
        Life's better with a backbeat! These spectacular song-and-dance
        sensations prove that when the music hits, anything is possible. From
        Broadway to back alleys, every moment's a show-stopper and every scene's
        a finale.
  Live & Unfiltered:
    template:
      name: Genre - Trakt List
      list: live-unfiltered
      summary: >-
        Take a front-row seat for comedy without a safety net! These fearless
        funny folks turn life's chaos into pure hilarity, armed with nothing but
        a mic and razor-sharp wit. Every joke lands, every story kills, and
        nothing is off limits.
    smart_label: title.asc
  Trick-or-Treat:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-halloween
      summary: >-
        Light up the jack-o’-lanterns for chills and thrills! These eerie flicks
        are packed with ghouls and goblins that’ll leave you shiverin’ with
        delight. It’s a screamfest that’s to die for!
  Turkey Lurkey Time:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-thanksgiving
      summary: >-
        Gather 'round for heartwarming tales, family feasts, and holiday
        hijinks! These festive flicks are packed with gratitude, gravy, and just
        the right amount of family drama. It's a cozy cornucopia of feel-good
        fun!
  Turn It Up:
    template:
      name: Genre - Trakt List
      list: movies-music
      item_genre: Music
      summary: >-
        Immerse yourself in the world of music with a mix of live concerts,
        biopics, and fictional films, showcasing thrilling moments on stage and
        captivating stories inspired by the power of music.
    smart_label: title.asc
  Total Tension:
    template:
      name: Genre
      genre: Thriller
      summary: >-
        Take a deep breath - it might be your last! These pulse-pounding
        thrillers turn every moment into a countdown and every choice into a
        deadly game. Between conspiracy and paranoia, trust becomes the ultimate
        weapon. Just remember: the truth is never what it seems.
  'Wanted: Dead or Alive':
    template:
      name: Genre
      genre: Western
      summary: >-
        Saddle up for a rootin'-tootin' adventure! These rugged tales are packed
        with dusty trails, quick-draw showdowns, and outlaws with grit. It's the
        wild frontier, where legends are born and the spirit of the Old West
        rides on!
