templates:
  Genre:
    optional:
      - label
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    label: <<label>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - label
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    label: <<label>>
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    optional:
      - label
      - summary
    label: <<label>>
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  Genre - Trakt List:
    optional:
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    label: <<label>>
    smart_label: release.asc
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  Genre - Trakt List Other:
    optional:
      - label
      - summary
    trakt_list: <<list>>
    sync_mode: sync
    label: <<label>>
    smart_label: release.asc
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    optional:
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    label: <<label>>
    smart_label: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Holiday] - Trakt List':
    optional:
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    label: <<label>>
    smart_label: title.asc
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List [Hide Items]':
    optional:
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: hide_items
    label: <<label>>
    item_genre: <<collection_name>>
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List Episodes':
    optional:
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: custom
    label: <<label>>
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
collections:
  Adventure Seekers:
    template:
      name: Genre
      genre: Adventure
      summary: >-
        From mystical realms to unexplored frontiers, adventure films thrust
        everyday heroes into extraordinary journeys. Where danger lurks,
        discovery follows. Buckle up for the ride.
  Bound to Be Seen:
    template:
      name: Genre - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-books'
      summary: >-
        Stories that couldn't be contained by puny book covers. Watch as beloved
        tales break free from their paper prisons and gain special effects,
        soundtracks, and occasionally questionable casting choices.
  Clue Me In:
    template:
      name: Genre
      genre: Mystery
      summary: >-
        Whodunnit? Get ready for a ride full of twists, turns, and sleuthing
        galore. These mystery films will have you on the edge of your seat,
        piecing together clues and unraveling the truth before the final reveal.
  Comic Book Legends:
    template:
      name: Genre - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-comics'
      summary: >-
        From basement collections to blockbuster phenomena. These comic
        adaptations span from game-changing masterpieces to endearingly
        misguided swings, each adding their own flavor to the multiverse.
  Criminal Intent:
    template:
      name: Genre
      genre: Crime
      summary: >-
        Get ready for gritty heists, dirty deals, and criminals with nothing to
        lose. These films dive deep into the underworld, where the stakes are
        high, and the law is nowhere to be found.
  Femme Fatale:
    template:
      name: Genre - Trakt List
      list: femme-fatale
      summary: >-
        Dangerous curves and deadlier motives. These sirens prove lipstick and
        lingering eye contact outgun any weapon. Watch brilliant men lose all
        reason, sealing their doom when they mistake predator for prey.
  Full Throttle:
    template:
      name: Genre
      genre: Action
      summary: >-
        Maximum velocity, minimum restraint! These action spectacles pack
        impossible stunts, endless ammunition, and directors who consider
        'subtle' a dirty word.
  Game Changers:
    template:
      name: Genre
      genre: Sports
      list: movies-sports
      summary: >-
        These films span all facets of sports, from heart-pounding drama to
        hilarious comedies and true stories of athletes who made their mark.
  Game Over:
    template:
      name: Genre - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-video-games'
      summary: >-
        Grab your popcorn, player one! These flicks bring the game screen to the
        big screen—packed with pixelated thrills and joystick joyrides!
  Hidden Gems:
    template:
      name: Genre - Trakt List
      list: movies-hidden-gems
      summary: >-
        Discover underrated treasures and overlooked classics waiting to shine
        on your screen!
  Laugh Out Loud:
    template:
      name: Genre
      genre: Comedy
      summary: >-
        Comedy roulette: spin the wheel and take your chances. From comedy's
        hall of fame to its hall of shame, these films deliver both masterful
        timing and spectacular misfires in their quest for laughter.
  Live & Unfiltered:
    template:
      name: Genre - Trakt List
      list: live-unfiltered
      summary: >-
        Raw comedy captured in its natural habitat. These mic-wielding
        risk-takers transform uncomfortable truths into unstoppable laughter
        with nothing but their wits and questionable life choices.
    smart_label: title.asc
  Magic & Myth:
    template:
      name: Genre
      genre: Fantasy
      summary: >-
        Step into a world where magic is real and myths come alive. These films
        transport you to realms filled with legendary creatures, enchanted
        lands, and epic quests.
  Noir or Never:
    template:
      name: Genre - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/film-noir-movies'
      summary: >-
        The dark corners of human desire, framed in shadow and cynicism. These
        moody masterpieces feature razor-sharp dialogue, fatal attractions, and
        the kind of nightmares that wear elegant suits.
  Out of This World:
    template:
      name: Genre - Trakt List
      list: live-unfiltered
      summary: >-
        Raw comedy captured in its natural habitat. These mic-wielding
        risk-takers transform uncomfortable truths into unstoppable laughter
        with nothing but their wits and questionable life choices.
    smart_label: title.asc
  Plunder & Peril:
    template:
      name: Genre - Trakt List
      list: plunder-peril
      summary: >-
        Hoist the black flag for a treasure trove of maritime mayhem! From
        swashbuckling adventures to deadly sea battles, these salty tales
        showcase the ultimate ocean outlaws in action. Just remember - dead men
        tell no tales.
  Portrait Gallery:
    template:
      name: Genre - Trakt List
      list: portrait-gallery
      smart_label: title.desc
      summary: >-
        From humble beginnings to legendary status, these intimate portraits
        capture the rise, fall, and resurrection of cultural icons. Watch raw
        talent transform into stardom as ordinary people become extraordinary
        legends. Every breakthrough, breakdown, and comeback crafted these
        unforgettable legacies.
  'Real Events, Reel Stories':
    template:
      name: Genre - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-true-stories'
      summary: >-
        True tales hit the silver screen! From heart-pounding heroics to wild
        twists of fate, these flicks bring real-life moments to movie magic!
  Holiday Hijinks:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: season-s-greetings
      smart_label: title.asc
      summary: >-
        Tinsel-covered chaos with a side of nog. These seasonal selections
        capture December's beautiful complexity—family reunions, heightened
        emotions, and the magic when holiday plans veer off course.
  Show Time:
    template:
      name: Genre - Trakt List
      list: show-time
      summary: >-
        Glorious emotion amplified through melody! These dazzling spectacles
        transport ordinary moments into sequined showcases where feelings
        deserve choreography and life's soundtrack includes a full orchestra.
  'So Bad, It''s Good':
    template:
      name: Genre - Trakt List
      list: bad-movies-collection
      summary: >-
        Get ready for a collection of hilariously awful films that are just
        plain shit! With epic fails and laugh-out-loud moments, these gems are
        perfect for a night of guilty pleasure!
  Trick-or-Treat:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-halloween
      summary: >-
        Light up the jack-o’-lanterns for chills and thrills! These eerie flicks
        are packed with ghouls and goblins that’ll leave you shiverin’ with
        delight. It’s a screamfest that’s to die for!
  Turkey Time:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-thanksgiving
      summary: >-
        Gather 'round for heartwarming tales, family feasts, and holiday
        hijinks! These festive flicks are packed with gratitude, gravy, and just
        the right amount of family drama. It's a cozy cornucopia of feel-good
        fun!
  Turn It Up:
    template:
      name: Genre - Trakt List
      list: movies-music
      item_genre: Music
      summary: >-
        Immerse yourself in the world of music with a mix of live concerts,
        biopics, and fictional films, showcasing thrilling moments on stage and
        captivating stories inspired by the power of music.
    smart_label: title.asc
  Total Tension:
    template:
      name: Genre
      genre: Thriller
      summary: >-
        Take a deep breath - it might be your last! These pulse-pounding
        thrillers turn every moment into a countdown and every choice into a
        deadly game. Between conspiracy and paranoia, trust becomes the ultimate
        weapon. Just remember: the truth is never what it seems.
  'Wanted: Dead or Alive':
    template:
      name: Genre
      genre: Western
      summary: >-
        Saddle up for a rootin'-tootin' adventure! These rugged tales are packed
        with dusty trails, quick-draw showdowns, and outlaws with grit. It's the
        wild frontier, where legends are born and the spirit of the Old West
        rides on!
  Wired Differently:
    template:
      name: Genre - Trakt List
      list: wired-differently
      summary: >-
        Stories where different wiring makes life more interesting, not broken.
        When everyday experiences hit different and social scripts need constant
        rewrites, these titles showcase minds that bring something fresh just by
        being themselves. No fixing required.
    label: Hide
    item_label: Hide
