templates:
  Genre:
    optional:
      - collection_order
      - item_genre
      - item_label
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: '!_Genre <<collection_name>>'
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - collection_order
      - item_genre
      - item_label
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: ~_Genre <<collection_name>>
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    summary: <<summary>>
  Genre - Trakt List:
    default:
      smart_label: release.asc
    optional:
      - item_genre
      - item_label
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    sort_title: '!_Genre <<collection_name>>'
    smart_label: <<smart_label>>
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    label: <<label>>
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    default:
      smart_label: release.asc
    optional:
      - item_genre
      - item_label
      - label
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    sort_title: ~_Genre <<collection_name>>
    smart_label: <<smart_label>>
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    label: <<label>>
    summary: <<summary>>
  Genre - Trakt List Episodes:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
collections:
  Christmas:
    template:
      name: Genre - Trakt List
      list: movies-christmas
      item_genre: Christmas
      smart_label: title.asc
      summary: Merry Christmas! Sh*tter was full.
