templates:
  Genre:
    smart_filter:
      all:
        genre: <<genre>>
        genre.not: Stand-Up
      sort_by: random
    sort_title: ~_<<collection_name>>
    only_run_on_create: true
    collection_mode: hide_items
    optional:
      - collection_order
      - item_genre
      - item_label
      - summary
      - trakt_list
    collection_order: <<collection_order>>
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    trakt_list: <<trakt_list>>
    summary: <<summary>>
  Genre - Trakt List:
    trakt_list: <<list>>
    sync_mode: sync
    sort_title: ~_<<collection_name>>
    collection_mode: hide_items
    optional:
      - collection_order
      - item_genre
      - item_label
      - label
      - summary
    collection_order: <<collection_order>>
    item_genre: <<item_genre>>
    item_label: <<item_label>>
    label: <<label>>
    summary: <<summary>>
collections:
  Action:
    template:
      name: Genre
      genre: Action
      summary: null
  Christmas:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-christmas'
      collection_order: alpha
      summary: Merry Christmas! Sh*tter was full.
    sort_title: ++_4.5Christmas
  Comedy:
    template:
      name: Genre
      genre: Comedy
      summary: null
  Crime:
    template:
      name: Genre
      genre: Crime
      summary: null
  Fantasy:
    template:
      name: Genre
      genre: Fantasy
      summary: null
  Halloween:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-halloween'
      collection_order: alpha
      item_genre: Halloween
      summary: '“Oh, look. Another glorious morning. Makes me sick!”'
    sort_title: ++_4.5Halloween
  Music:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/music'
      item_genre: Music
      summary: "\U0001F3B8"
    sort_title: ++_4.5Music
  Musical:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-musicals'
      item_genre: Musical
      summary: 'If you know what you want, then you go and you find it and you get it.'
    sort_title: ++_4.5Musical
  Mystery:
    template:
      name: Genre
      genre: Mystery
      summary: null
  Sci-Fi:
    template:
      name: Genre
      genre: Sci-Fi
      summary: null
  Sports:
    template:
      name: Genre
      genre: Sports
      item_genre: Sports
      trakt_list: 'https://trakt.tv/users/goape/lists/movies-sports'
      summary: null
    sort_title: ++_4.5Sports
  Stand Up Comedy:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-standup'
      item_genre: Stand-Up
      summary: null
    sort_title: ++_4.5Stand Up Comedy
  Thanksgiving:
    template:
      name: Genre - Trakt List
      list: 'https://trakt.tv/users/goape/lists/movies-thanksgiving'
      collection_order: alpha
      item_genre: Thanksgiving
      summary: '“Gobble, gobble!”'
    sort_title: ++_4.5Thanksgiving
  Thriller:
    template:
      name: Genre
      genre: Thriller
      summary: null
  Western:
    template:
      name: Genre
      genre: Western
      summary: null
