templates:
  Genre:
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom]':
    optional:
      - summary
    smart_filter:
      all:
        genre: <<genre>>
      sort_by: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Bottom] - Custom':
    optional:
      - summary
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  Genre - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: release.asc
    item_genre: <<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  Genre - Trakt List Other:
    optional:
      - summary
    trakt_list: <<list>>
    sync_mode: sync
    smart_label: release.asc
    item_genre: <<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
    summary: <<summary>>
  'Genre [Bottom] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: random
    sort_title: ~_Genre <<collection_name>>
    summary: <<summary>>
  'Genre [Holiday] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    smart_label: title.asc
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List [Hide Items]':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_mode: hide_items
    item_genre: <<collection_name>>
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
  'Genre [Holiday] - Trakt List Episodes':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    builder_level: episode
    collection_order: custom
    sort_title: '!3_Genre_Holiday <<collection_name>>'
    summary: <<summary>>
collections:
  Brains!:
    template:
      name: Genre - Trakt List
      list: brains
      summary: >-
        “Get ready for a feast of flesh-eating mayhem! These undead thrillers
        are packed with groaning ghouls, slow-moving terror, and plenty of
        brain-munching action. It’s the perfect collection for those who like
        their horror with a side of bite!”
    smart_label: title.asc
  Clowning Around:
    template:
      name: Genre - Trakt List
      list: clowning-around
      summary: >-
        Step right up and enjoy the show! These clown-filled films are full of
        fun, mischief, and a touch of the unexpected. Laughter is guaranteed,
        but who knows what’s lurking under that painted smile?
    smart_label: title.asc
  Bloodsuckers & Fangs:
    template:
      name: Genre - Trakt List
      list: bloodsuckers-fangs
      summary: >-
        Step into the shadows and face the creatures of the night! These movies
        deliver spine-chilling thrills, with vampires lurking in every corner.
    smart_label: title.asc
  Season's Greetings:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-horror-christmas
      summary: >-
        'Tis the season… for terror! These bloody yuletide tales take holiday
        cheer to the darkest depths, with killer Santas, twisted carols, and
        enough gore to stain the snow red. It's festive as hell—just the way
        Krampus intended!
  Trick-or-Treat:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-halloween
      summary: >-
        Get ready for a bloodbath! These brutal flicks bring the gore, guts, and
        nightmares. From pissed-off ghosts to slashers who won't quit, it's
        wall-to-wall horror with enough twisted shit to haunt you long after
        Halloween's over.
  Turkey Lurkey Time:
    template:
      name: 'Genre [Holiday] - Trakt List'
      list: movies-horror-thanksgiving
      summary: >-
        Gather 'round for heartwarming tales, family feasts, and holiday
        hijinks! These festive flicks are packed with gratitude, gravy, and just
        the right amount of family drama. It's a cozy cornucopia of feel-good
        fun!
  Horror:
    template:
      name: 'Genre [Bottom] - Custom'
      summary: >-
        Step right up to the spook show! From ghouls and goblins to
        bone-crackin' killers, this freaky lineup serves up every scream in the
        book. Get your kicks with blood-curdling classics, monster mashes, and
        gore galore—it's a real scream scene, daddy-o!
    smart_filter:
      all:
        title.not: Gamboozle
        sort_by: random
  Howl at the Moon:
    template:
      name: Genre - Trakt List
      list: howl-at-the-moon
      summary: >-
        Brace for a wild, fur-filled frenzy! These frightful flicks bring on
        beastly transformations, full moons, and chills that’ll have you
        questioning who—or what—is lurking in the shadows. It’s a supernatural
        adventure where danger lurks beneath every howl!
    smart_label: title.asc
  Musical:
    template:
      name: Genre - Trakt List
      list: movies-musicals
      name_mapping: Musical Horror
      summary: null
