templates:
  Network:
    tmdb_network: <<network>>
    sort_title: ++_5.5<<collection_name>>
    smart_label: year.asc
    optional:
      - tmdb_movie
      - trakt_list
      - summary
    tmdb_movie: <<tmdb_movie>>
    trakt_list: <<trakt_list>>
    summary: <<summary>>
  Network - Trakt List:
    trakt_list: <<list>>
    sort_title: ++_5.5<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
collections:
  Hallmark Channel:
    template:
      name: Network
      network: 4056
      tmdb_movie: '317114, 594695, 361746, 609434, 663566'
      trakt_list: 'https://trakt.tv/users/goape/lists/movies-hallmark'
  Lifetime:
    template:
      name: Network
      network: 3431
