templates:
  Network:
    tmdb_network: <<network>>
    sort_title: ++_5.5<<collection_name>>
    smart_label: year.asc
    optional:
      - tmdb_movie
      - trakt_list
      - summary
    tmdb_movie: <<tmdb_movie>>
    trakt_list: <<trakt_list>>
    summary: <<summary>>
  Network - Trakt List:
    trakt_list: <<list>>
    sort_title: ++_5.5<<collection_name>>
    smart_label: year.asc
    optional:
      - summary
    summary: <<summary>>
collections:
  History:
    template:
      name: Network
      network: '65, 849'
