templates:
  Network:
    optional:
      - tmdb_movie
      - list
      - summary
    tmdb_network: <<network>>
    tmdb_movie: <<tmdb_movie>>
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    smart_label: year.asc
    sort_title: '!5.5_Network: <<collection_name>>'
    summary: <<summary>>
  Network - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    smart_label: year.asc
    sort_title: '!5.5_Network: <<collection_name>>'
    summary: <<summary>>
collections:
  Bravo:
    template:
      name: Network
      network: 74
  Disney Channel:
    template:
      name: Network
      network: 54
      summary: >-
        Disney Channel (originally called The Disney Channel from 1983 to 1997
        and commonly shortened to Disney from 1997 to 2002) is an American pay
        television channel that serves as the flagship property of owner Disney
        Branded Television, a unit of the Disney General Entertainment Content
        division of The Walt Disney Company.
  History:
    template:
      name: Network
      network: '65, 849'
  Nickelodeon:
    template:
      name: Network
      network: 13
      summary: 'Nick, Nick, Nick, Nick, Ni-, Nick, Nick, Nick Nickelodeon'
