templates:
  Network:
    tmdb_network: <<network>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_7<<collection_name>>
  Network - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_7<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  History:
    template:
      name: Network
      network: '65, 849'
