templates:
  Network:
    tmdb_network: <<network>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_7<<collection_name>>
    optional:
      - tmdb_movie
      - trakt_list
      - summary
    tmdb_movie: <<tmdb_movie>>
    trakt_list: 'https://trakt.tv/users/goape/lists/<<trakt_list>>'
    summary: <<summary>>
  Network - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_7<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Hallmark Channel:
    template:
      name: Network
      network: 4056
      tmdb_movie: '317114, 594695, 361746, 609434, 663566'
      trakt_list: movies-hallmark
  Lifetime:
    template:
      name: Network
      network: 3431
