templates:
  Network:
    tmdb_network: <<network>>
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_5.5<<collection_name>>
    optional:
      - tmdb_movie
      - trakt_list
      - summary
    tmdb_movie: <<tmdb_movie>>
    trakt_list: 'https://trakt.tv/users/goape/lists/<<trakt_list>>'
    summary: <<summary>>
  Network - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    collection_order: release
    collection_mode: hide_items
    sort_title: ++_5.5<<collection_name>>
    optional:
      - summary
    summary: <<summary>>
collections:
  Bravo:
    template:
      name: Network
      network: 74
  Disney Channel:
    template:
      name: Network
      network: 54
      summary: >-
        Disney Channel (originally called The Disney Channel from 1983 to 1997
        and commonly shortened to Disney from 1997 to 2002) is an American pay
        television channel that serves as the flagship property of owner Disney
        Branded Television, a unit of the Disney General Entertainment Content
        division of The Walt Disney Company.
    show_filtered: true
    filters:
      title.not:
        - Disneyland
        - 'Good Morning, Miss Bliss'
  History:
    template:
      name: Network
      network: '65, 849'
    filters:
      title.not:
        - The Adventures of Young Indiana Jones
  Nickelodeon:
    template:
      name: Network
      network: 13
      summary: 'Nick, Nick, Nick, Nick, Ni-, Nick, Nick, Nick Nickelodeon'
