Collection - Movie:
  tmdb_collection: <<collection>>
  tmdb_movie: <<movie>>
  sync_mode: sync
  collection_order: release
  default:
    collection_mode: hide_items
  optional:
    - label
    - name_mapping
    - sort_title
    - summary
  label: <<label>>
  name_mapping: <<name_mapping>>
  sort_title: <<sort_title>>
  summary: <<summary>>
Collection - Movies:
  tmdb_movie: <<movie>>
  sync_mode: sync
  collection_order: release
  default:
    collection_mode: hide_items
  optional:
    - name_mapping
    - sort_title
    - summary
  name_mapping: <<name_mapping>>
  sort_title: <<sort_title>>
  summary: <<summary>>
Collection - Hide Movie:
  optional:
    - movie
    - collection
    - name_mapping
    - sort_title
    - summary
  tmdb_movie: <<movie>>
  tmdb_collection: <<collection>>
  sync_mode: sync
  collection_order: release
  collection_mode: hide
  name_mapping: <<name_mapping>>
  sort_title: <<sort_title>>
  summary: <<summary>>
