First - Custom:
  optional:
    - sort_title
    - summary
  sort_title: '!_First <<collection_name>>'
  summary: <<summary>>
'First [Sort Title] - Custom':
  optional:
    - sort_title
    - summary
  sort_title: '!_First <<sort_title>>'
  summary: <<summary>>
