Genre:
  default:
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
  optional:
    - item_genre
    - item_label
    - label
    - sort_title
    - summary
  smart_filter:
    all:
      genre: <<genre>>
    sort_by: random
  item_genre: Genre_<<item_genre>>
  item_label: Genre_<<item_label>>
  label: Genre_<<label>>
  sort_title: '!3_Genre <<custom_sort_title>>'
  summary: <<summary>>
'Genre [Bottom]':
  default:
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: '!3_Genre <<collection_name>>'
  optional:
    - item_genre
    - item_label
    - label
    - sort_title
    - summary
  smart_filter:
    all:
      genre: <<genre>>
    sort_by: random
  item_genre: Genre_<<item_genre>>
  item_label: Genre_<<item_label>>
  label: Genre_<<label>>
  sort_title: ~_Genre <<custom_sort_title>>
  summary: <<summary>>
'Genre [Bottom] - Custom':
  default:
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: ~_Genre <<collection_name>>
  optional:
    - item_genre
    - item_label
    - label
    - sort_title
    - summary
  item_genre: Genre_<<item_genre>>
  item_label: Genre_<<item_label>>
  label: Genre_<<label>>
  sort_title: ~_Genre <<custom_sort_title>>
  summary: <<summary>>
Genre - Trakt List:
  default:
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    smart_label: release.asc
    sort_title: '!3_Genre <<collection_name>>'
  optional:
    - item_genre
    - item_label
    - label
    - smart_label
    - sort_title
    - summary
  trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
  sync_mode: sync
  smart_label: <<smart_label>>
  item_genre: <<item_genre>>
  item_label: Genre_<<item_label>>
  label: Genre_<<label>>
  sort_title: '!3_Genre <<custom_sort_title>>'
  summary: <<summary>>
'Genre [Bottom] - Trakt List':
  default:
    item_genre: <<collection_name>>
    item_label: Genre_<<collection_name>>
    label: Genre_<<collection_name>>
    sort_title: ~_Genre <<collection_name>>
    smart_label: release.asc
  optional:
    - item_genre
    - item_label
    - label
    - smart_label
    - sort_title
    - summary
  trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
  sync_mode: sync
  smart_label: <<smart_label>>
  item_genre: <<item_genre>>
  item_label: <<item_label>>
  label: <<label>>
  sort_title: ~_Genre <<custom_sort_title>>
  summary: <<summary>>
Genre - Trakt List Episodes:
  trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
  sync_mode: sync
  builder_level: episode
  collection_order: alpha
  collection_level: episode
