Genre:
  default:
    custom_item_genre: <<collection_name>>
    custom_item_label: Genre_<<collection_name>>
    custom_label: Genre_<<collection_name>>
    custom_sort_title: '!3_Genre <<collection_name>>'
  optional:
    - summary
  smart_filter:
    all:
      genre: <<genre>>
    sort_by: random
  item_genre: Genre_<<custom_item_genre>>
  item_label: Genre_<<custom_item_label>>
  label: Genre_<<custom_label>>
  sort_title: '!3_Genre <<custom_sort_title>>'
  summary: <<summary>>
'Genre [Bottom]':
  default:
    custom_item_genre: <<collection_name>>
    custom_item_label: Genre_<<collection_name>>
    custom_label: Genre_<<collection_name>>
    custom_sort_title: '!3_Genre <<collection_name>>'
  optional:
    - summary
  smart_filter:
    all:
      genre: <<genre>>
    sort_by: random
  item_genre: Genre_<<custom_item_genre>>
  item_label: Genre_<<custom_item_label>>
  label: Genre_<<custom_label>>
  sort_title: ~_Genre <<custom_sort_title>>
  summary: <<summary>>
'Genre [Bottom] - Custom':
  default:
    custom_item_genre: <<collection_name>>
    custom_item_label: Genre_<<collection_name>>
    custom_label: Genre_<<collection_name>>
    custom_sort_title: ~_Genre <<collection_name>>
  optional:
    - summary
  item_genre: Genre_<<custom_item_genre>>
  item_label: Genre_<<custom_item_label>>
  label: Genre_<<custom_label>>
  sort_title: ~_Genre <<custom_sort_title>>
  summary: <<summary>>
Genre - Trakt List:
  default:
    custom_item_genre: <<collection_name>>
    custom_item_label: Genre_<<collection_name>>
    custom_label: Genre_<<collection_name>>
    custom_smart_label: release.asc
    custom_sort_title: '!3_Genre <<collection_name>>'
  optional:
    - summary
  trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
  sync_mode: sync
  smart_label: <<custom_smart_label>>
  item_genre: Genre_<<custom_item_genre>>
  item_label: Genre_<<custom_item_label>>
  label: Genre_<<custom_label>>
  sort_title: '!3_Genre <<custom_sort_title>>'
  summary: <<summary>>
'Genre [Bottom] - Trakt List':
  default:
    custom_item_genre: <<collection_name>>
    custom_item_label: Genre_<<collection_name>>
    custom_label: Genre_<<collection_name>>
    custom_sort_title: ~_Genre <<collection_name>>
    custom_smart_label: release.asc
  optional:
    - summary
  trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
  sync_mode: sync
  smart_label: <<custom_smart_label>>
  item_genre: Genre_<<custom_item_genre>>
  item_label: <<item_label>>
  label: <<label>>
  sort_title: ~_Genre <<custom_sort_title>>
  summary: <<summary>>
Genre - Trakt List Episodes:
  trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
  sync_mode: sync
  builder_level: episode
  collection_order: alpha
  collection_level: episode
