Search:
  plex_search:
    title: <<title>>
  sync_mode: sync
  collection_order: release
  default:
    collection_mode: hide_items
  optional:
    - name_mapping
    - sort_title
    - summary
  name_mapping: <<name_mapping>>
  sort_title: <<sort_title>>
  summary: <<summary>>
