overlays:
  Dutch:
    overlay:
      name: Dutch
      file: config/overlays/Languages/dutch-overlay-v2.png
    plex_search:
      all:
        audio_language: nl
        audio_language.not: en
  French:
    overlay:
      name: French
      file: config/overlays/Languages/french-overlay-v2.png
    plex_search:
      all:
        any:
          title: The Count of Monte-Cristo
        all:
          audio_language: fr
          audio_language.not: en
          country: fr
  German:
    overlay:
      name: German
      file: config/overlays/Languages/german-overlay-v2.png
    plex_search:
      all:
        audio_language: de
        audio_language.not: en
  Icelandic:
    overlay:
      name: Icelandic
      file: config/overlays/Languages/icelandic-overlay-v2.png
    plex_search:
      all:
        audio_language: is
        audio_language.not: en
  Italian:
    overlay:
      name: Italian
      file: config/overlays/Languages/italian-overlay-v2.png
    plex_search:
      all:
        audio_language: it
        audio_language.not: en
  Japanese:
    overlay:
      name: Japanese
      file: config/overlays/Languages/japanese-overlay-v2.png
    plex_search:
      all:
        audio_language: ja
        audio_language.not: en
  Korean:
    overlay:
      name: Korean
      file: config/overlays/Languages/korean-overlay-v2.png
    plex_search:
      all:
        audio_language: ko
        audio_language.not: en
  Russian:
    overlay:
      name: Russian
      file: config/overlays/Languages/russian-overlay-v2.png
    plex_search:
      all:
        audio_language: ru
        audio_language.not: en
  Spanish:
    overlay:
      name: Spanish
      file: config/overlays/Languages/spanish-overlay-v2.png
    plex_search:
      all:
        audio_language: es
        audio_language.not: en
  Swedish:
    overlay:
      name: Swedish
      file: config/overlays/Languages/swedish-overlay-v2.png
    plex_search:
      all:
        audio_language: sv
        audio_language.not: en
