templates:
  Category - Custom:
    optional:
      - summary
    sort_title: '!3.5_Category <<collection_name>>'
    summary: <<summary>>
  Category - Trakt List:
    optional:
      - name_mapping
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    name_mapping: <<name_mapping>>
    sort_title: '!3.5_Category <<collection_name>>'
    smart_label: year.asc
    summary: <<summary>>
  Category - Trakt List Other:
    optional:
      - name_mapping
      - summary
    trakt_list: <<list>>
    sync_mode: sync
    name_mapping: <<name_mapping>>
    sort_title: '!3.5_Category <<collection_name>>'
    smart_label: title.asc
    summary: <<summary>>
  Category - Trakt List Custom Order:
    optional:
      - name_mapping
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    sort_title: '!3.5_Category <<collection_name>>'
    collection_mode: show_items
    name_mapping: <<name_mapping>>
    summary: <<summary>>
  Category - Trakt List Custom Order Details:
    optional:
      - name_mapping
      - summary
    trakt_list_details: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    collection_mode: show_items
    name_mapping: <<name_mapping>>
    sort_title: '!3.5_Category <<collection_name>>'
    summary: <<summary>>
  Category - Letterboxd List:
    optional:
      - name_mapping
      - summary
    letterboxd_list: <<list>>
    sync_mode: sync
    collection_order: custom
    collection_mode: show_items
    name_mapping: <<name_mapping>>
    sort_title: '!3.5_Category <<collection_name>>'
    summary: <<summary>>
  Category - IMDB List:
    optional:
      - name_mapping
      - summary
    letterboxd_list: 'https://www.imdb.com/<<list>>'
    sync_mode: sync
    smart_label: year.asc
    name_mapping: <<name_mapping>>
    sort_title: '!3.5_Category <<collection_name>>'
    summary: <<summary>>
collections:
  Awesomely Awful:
    template:
      name: Category - Trakt List
      list: bad-movies-collection
      summary: >-
        Get ready for a collection of hilariously awful films that are just
        plain shit! With epic fails and laugh-out-loud moments, these gems are
        perfect for a night of guilty pleasure!
  Bound to Be Seen:
    template:
      name: Category - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-books'
      summary: >-
        From page to screen, these beloved books come to life—get ready for
        timeless tales turned into cinematic magic!
  Certified Fresh:
    template:
      name: Category - Trakt List
      list: movies-certified-fresh
      summary: >-
        Snagging the golden seal of approval, these films are the crème de la
        crème! Certified fresh by Rotten Tomatoes, they offer an entertaining
        adventure that’s sure to keep you captivated—popcorn at the ready!
  Hidden Gems:
    template:
      name: Category - Trakt List
      list: movies-hidden-gems
      summary: >-
        Discover underrated treasures and overlooked classics waiting to shine
        on your screen!
  Comics Come Alive!:
    template:
      name: Category - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-comics'
      summary: >-
        Zap! Bang! Boom! These larger-than-life adventures leap from comic
        panels to the big screen, packed with heroes, hijinks, and high-flying
        action!
  'Real Events, Reel Stories':
    template:
      name: Category - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-true-stories'
      summary: >-
        True tales hit the silver screen! From heart-pounding heroics to wild
        twists of fate, these flicks bring real-life moments to movie magic!
  Game Over:
    template:
      name: Category - Trakt List Other
      list: 'https://trakt.tv/users/k0meta/lists/movies-based-on-video-games'
      summary: >-
        Grab your popcorn, player one! These flicks bring the game screen to the
        big screen—packed with pixelated thrills and joystick joyrides!
