templates:
  Collection:
    default:
      collection_mode: hide_items
    optional:
      - label
      - name_mapping
      - sort_title
      - summary
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    minimum_items: 2
    name_mapping: <<name_mapping>>
    label: <<label>>
    sort_title: <<sort_title>>
    tmdb_summary: <<collection>>
    summary: <<summary>>
  Collection - Alpha:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: alpha
    minimum_items: 2
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Release:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    minimum_items: 2
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: release
    collection_mode: <<collection_mode>>
    default:
      collection_mode: hide_items
    optional:
      - label
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    label: <<label>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    default:
      collection_mode: hide_items
    optional:
      - label
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    label: <<label>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Movie:
    tmdb_collection: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - label
      - name_mapping
      - sort_title
      - summary
    label: <<label>>
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Movies:
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - label
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    label: <<label>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Hide Movie:
    optional:
      - label
      - movie
      - collection
      - name_mapping
      - sort_title
      - summary
    tmdb_movie: <<movie>>
    tmdb_collection: <<collection>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    name_mapping: <<name_mapping>>
    label: <<label>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
  Unmanaged:
    label: Unmanaged
    blank_collection: true
  Unmanaged - Horror:
    label: 'Unmanaged, Horror'
    blank_collection: true
unmanaged: &ref_0
  template:
    name: Unmanaged
collections:
  Anne of Green Gables Collection:
    template:
      name: Search
      title: Anne of Green Gables
  Book Club Collection: *ref_0
  Bridget Jones Collection: *ref_0
  Christmas in Evergreen Collection: *ref_0
  A Gift to Remember Collection: *ref_0
  A Godwink Christmas Collection: *ref_0
  The Mistletoe Collection: *ref_0
  Mrs. Miracle Collection: *ref_0
  Northpole Collection: *ref_0
  'Sarah, Plain and Tall Collection': *ref_0
  Sister Swap Collection: *ref_0
  Time for Me to Come Home Collection: *ref_0
  Delete:
    build_collection: false
    smart_filter:
      all:
        release: 1
    delete_collections_named:
      - At Graceland Collection
      - The Bridge Collection
      - Christmas in Canaan Collection
      - Haul Out The Holly Collection
      - L.M. Montgomery's Anne of Green Gables Collection
      - Mr. Darcy Collection
      - The Nine Lives of Christmas Collection
      - Signed Sealed Delivered Collection
      - Single Santa Seeks Mrs. Claus Collection
      - A Town Without Christmas Collection
      - Three Wise Men Collection
