templates:
  Collection:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Alpha:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Release:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Movie:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Movies:
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Hide:
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - sort_title
      - summary
    sort_title: <<sort_title>>
    summary: <<summary>>
collections:
  'Love, Simon Collection':
    template:
      name: Collection - Hide
      movie: 449176
