templates:
  Collection:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Alpha:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: alpha
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Release:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: release
    collection_mode: <<collection_mode>>
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Movie:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Movies:
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Hide Movie:
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
collections:
  Anne of Green Gables Collection:
    template:
      name: Search
      title: Anne of Green Gables
