metadata:
  A Christmas Story:
    sort_title: A Christmas Story 1
  'Home Alone: The Holiday Heist':
    sort_title: Home Alone 5
  The 'Burbs:
    sort_title: Burbs
  '*batteries not included':
    sort_title: batteries not included
