templates:
  List - Custom:
    optional:
      - summary
    sort_title: '!6_List <<collection_name>>'
    summary: <<summary>>
  List - Trakt List:
    optional:
      - name_mapping
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    name_mapping: <<name_mapping>>
    sort_title: '!6_List <<collection_name>>'
    smart_label: year.asc
    summary: <<summary>>
  List - Trakt List Custom Order:
    optional:
      - name_mapping
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    sort_title: '!6_List <<collection_name>>'
    collection_mode: show_items
    name_mapping: <<name_mapping>>
    summary: <<summary>>
  List - Trakt List Custom Order Details:
    optional:
      - name_mapping
      - summary
    trakt_list_details: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    collection_mode: show_items
    name_mapping: <<name_mapping>>
    sort_title: '!6_List <<collection_name>>'
    summary: <<summary>>
  List - Letterboxd List:
    optional:
      - name_mapping
      - summary
    letterboxd_list: <<list>>
    sync_mode: sync
    collection_order: custom
    collection_mode: show_items
    name_mapping: <<name_mapping>>
    sort_title: '!6_List <<collection_name>>'
    summary: <<summary>>
  List - IMDB List:
    optional:
      - name_mapping
      - summary
    letterboxd_list: 'https://www.imdb.com/<<list>>'
    sync_mode: sync
    smart_label: year.asc
    name_mapping: <<name_mapping>>
    sort_title: '!6_List <<collection_name>>'
    summary: <<summary>>
collections:
  Empire Magazine's 100 Greatest TV Shows Of All Time:
    template:
      name: List - Trakt List Custom Order
      list: empire-magazine-s-100-greatest-tv-shows-of-all-time
      summary: >-
        It's true: we're living in a golden age of television. Some of the best
        TV series of all time have aired in the last few years – from
        character-driven dramas to big-budget sci-fi and fantasy shows with
        film-level production values – taking full advantage of the
        possibilities of long-form serialised storytelling. With cable-channel
        blockbusters, the arrival of streaming services, and the rise of
        idiosyncratic shows from diverse creators, the art of television is at
        an all-time high.

        We asked you to vote for your top 10 scripted TV shows (no reality telly
        here) of all time – stacking up your personal favourites, perennial
        re-watches, all-time greats and more. You responded in droves, and we
        tallied up the results into a Top 100 list bursting with incredible
        series you're bound to get hooked on. From iconic British sitcoms to
        epic American sagas, inventive animations and daring anthologies, these
        are the shows worth getting lost in, that have proved instrumental in
        evolving a storytelling form that continues to offer deeper and more
        complex narratives.
