templates:
  People:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_7<<collection_name>>
    summary: <<summary>>
  People - Actor:
    smart_filter:
      any:
        actor: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_7<<collection_name>>
    summary: <<summary>>
  People - Actor Trakt List:
    trakt_list: <<list>>
    sort_title: ++_7<<collection_name>>
    sync_mode: sync
    smart_label: release.asc
    summary: <<summary>>
  People - Actor Director:
    smart_filter:
      any:
        actor: <<person>>
        director: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_7<<collection_name>>
    summary: <<summary>>
  People - Director:
    smart_filter:
      any:
        director: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  People - Director Trakt List:
    trakt_list: <<list>>
    sort_title: ++_6<<collection_name>>
    sync_mode: sync
    smart_label: release.asc
    summary: <<summary>>
  People - Director Writer:
    smart_filter:
      any:
        director: <<person>>
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  People - Writer:
    smart_filter:
      any:
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  People - Actor Director Writer:
    smart_filter:
      any:
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
collections:
  Agatha Christie Collection:
    template:
      name: People
      title: 'Agatha Christie: 100 Years of Suspense'
  David Attenborough Collection:
    template:
      name: People
      title:
        - 'Planet Earth: A Celebration'
        - 'Breaking Boundaries: The Science of Our Planet'
  Marilyn Monroe Collection:
    template:
      name: People
      title: 'The Mystery of Marilyn Monroe: The Unheard Tapes'
  Stephen King Collection:
    template:
      name: People
      title: King on Screen
  Vincent Price Collection:
    template:
      name: People
      title: 'Vincent Price: The Versatile Villain'
