templates:
  People - Actor:
    smart_filter:
      any:
        actor: <<person>>
        title: <<title>>
      sort_by: release.asc
    smart_label: release.desc
    sort_title: ++_7<<collection_name>>
  People - Actor Trakt List:
    trakt_list: <<list>>
    sort_title: ++_7<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
  Actor List Documentary:
    sort_title: ++_7<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
  Actor All:
    tmdb_actor: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
    smart_label: release.desc
  Actor Director:
    tmdb_actor: <<id>>
    tmdb_director: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    smart_label: release.desc
  Actor Director Writer:
    tmdb_actor: <<id>>
    tmdb_director: <<id>>
    tmdb_writer: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    smart_label: release.desc
  Actor Writer:
    tmdb_actor: <<id>>
    tmdb_writer: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    smart_label: release.desc
  Director:
    tmdb_director: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    smart_label: release.desc
  Director List:
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
  Director Writer:
    tmdb_writer: <<id>>
    tmdb_director: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    smart_label: release.desc
  Writer:
    tmdb_writer: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_6<<collection_name>>
    smart_label: release.desc
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
collections:
  Don Bluth Collection:
    template:
      name: Director
      id: 40345
      person: Don Bluth
  Dr. Seuss Collection:
    template:
      name: Writer
      id: 65705
      person: Dr. Seuss
    trakt_list: 'https://trakt.tv/users/goape/lists/dr-seuss-collection'
    name_mapping: Dr Seuss Collection
  Julia Donaldson Collection:
    template:
      name: Writer
      id: 592851
      person: Julia Donaldson
