templates:
  Collection - Show:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Shows:
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - tvdb_show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    tvdb_show: <<tvdb_show>>
    summary: <<summary>>
  Collection - Hide Show:
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    optional:
      - name_mapping
      - sort_title
      - summary
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  People:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Title:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Actor:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
        actor: <<person>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Actor/Director/Writer:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Director:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
        director: <<person>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Director/Writer:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
        director: <<person>>
        writer: <<person>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Writer:
    optional:
      - title
      - person
      - summary
    smart_filter:
      any:
        title: <<title>>
        writer: <<person>>
      sort_by: release.asc
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Trakt List:
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    sync_mode: sync
    smart_label: release.asc
    summary: <<summary>>
  'People [Sort Title] - Trakt List':
    optional:
      - summary
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<sort_title>>'
    sync_mode: sync
    smart_label: release.asc
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
