templates:
  People:
    smart_filter:
      any:
        actor: <<collection_name>>
        director: <<collection_name>>
        writer: <<collection_name>>
        title: <<title>>
      sort_by: release.asc
    title: <<collection_name>> Collection
    sort_title: ++_7<<collection_name>>
    summary: <<summary>>
  People - Actor:
    smart_filter:
      any:
        actor: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_7<<collection_name>>
    summary: <<summary>>
  People - Actor Trakt List:
    trakt_list: <<list>>
    sort_title: ++_7<<collection_name>>
    sync_mode: sync
    smart_label: release.asc
    summary: <<summary>>
  People - Actor Director:
    smart_filter:
      any:
        actor: <<person>>
        director: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_7<<collection_name>>
    summary: <<summary>>
  People - Director:
    smart_filter:
      any:
        director: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  People - Director Trakt List:
    trakt_list: <<list>>
    sort_title: ++_6<<collection_name>>
    sync_mode: sync
    smart_label: release.asc
    summary: <<summary>>
  People - Director Writer:
    smart_filter:
      any:
        director: <<person>>
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  People - Writer:
    smart_filter:
      any:
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  People - Actor Director Writer:
    smart_filter:
      any:
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
        title: <<title>>
      sort_by: release.asc
    sort_title: ++_6<<collection_name>>
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
collections:
  Stephen King:
    template:
      name: People
      title: Stephen King's IT
  Wes Craven:
    template:
      name: Person
