templates:
  People:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Title:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Actor:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
        actor: <<person>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Actor/Director/Writer:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
        actor: <<person>>
        director: <<person>>
        writer: <<person>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Director:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
        director: <<person>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Director/Writer:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
        director: <<person>>
        writer: <<person>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Writer:
    optional:
      - list
      - person
      - summary
      - title
    smart_filter:
      any:
        title: <<title>>
        writer: <<person>>
      sort_by: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  People - Trakt List:
    optional:
      - summary
    sync_mode: sync
    smart_label: release.asc
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sort_title: '!7_People <<collection_name>>'
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
collections:
  Agatha Christie:
    template:
      name: People - Title
      title: Identity
  Dr. Seuss:
    template:
      name: People - Title
      title: The Mean One
