templates:
  Actor:
    tmdb_actor: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_8<<collection_name>>
  Actor List:
    sort_title: ++_8<<collection_name>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
  Actor List Documentary:
    sort_title: ++_8<<collection_name>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
  Actor All:
    tmdb_actor: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_8<<collection_name>>
  Actor Director:
    tmdb_actor: <<id>>
    tmdb_director: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
  Actor Director Writer:
    tmdb_actor: <<id>>
    tmdb_director: <<id>>
    tmdb_writer: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
  Actor Writer:
    tmdb_actor: <<id>>
    tmdb_writer: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
  Director:
    tmdb_director: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
  Director List:
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
  Director Writer:
    tmdb_writer: <<id>>
    tmdb_director: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
  Writer:
    tmdb_writer: <<id>>
    tmdb_biography: <<id>>
    sort_title: ++_7<<collection_name>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    default:
      collection_mode: hide_items
    optional:
      - name_mapping
      - sort_title
      - summary
      - show
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    summary: <<summary>>
    tmdb_show: <<show>>
collections:
  Agatha Christie Collection:
    tmdb_movie: 753489
    sort_title: ++_7Agatha Christie Collection
  Ken Burns Collection:
    template:
      name: Director Writer
      id: 204484
      person: Ken Burns
    tmdb_movie: 449434
  Steven Spielberg Collection:
    tmdb_movie: 467062
    sort_title: ++_7Steven Spielberg Collection
  Abbott and Costello Collection:
    template:
      name: Actor List Documentary
    trakt_list: 'https://trakt.tv/users/goape/lists/abbott-and-costello'
    tmdb_movie: 61433
    summary: >-
      Abbott and Costello were an American comedy duo composed of comedians Bud
      Abbott and Lou Costello, whose work on radio and in film and television
      made them the most popular comedy team of the 1940s and early 1950s and
      the highest-paid entertainers in the world during World War II.
  Charlie Chaplin Collection:
    tmdb_movie: 788396
    sort_title: ++_8Charlie Chaplin Collection
  David Attenborough Collection:
    trakt_list: 'https://trakt.tv/users/goape/lists/david-attenborough'
    sort_title: ++_8David Attenborough
  Dolly Parton Collection:
    tmdb_movie: 658092
    sort_title: ++_8Dolly Parton Collection
  Lucille Ball Collection:
    tmdb_movie: 736280
    sort_title: ++_8Lucille Ball Collection
  Marilyn Monroe Collection:
    tmdb_movie: 953300
    sort_title: ++_8Marilyn Monroe Collection
  Robin Williams Collection:
    tmdb_movie: 493100
    sort_title: ++_8Robin Williams Collection
  Vincent Price Collection:
    tmdb_movie: 436743
    sort_title: ++_8Vincent Price Collection
