templates:
  Collection:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Alpha:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Release:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Trakt List Custom Order:
    trakt_list: 'https://trakt.tv/users/goape/lists/<<list>>'
    sync_mode: sync
    collection_order: custom
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Show:
    tmdb_collection: 'https://www.themoviedb.org/collection/<<collection>>'
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Shows:
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Collection - Hide:
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
  Search:
    plex_search:
      title: <<title>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide_items
    optional:
      - name
      - sort_title
      - summary
    name_mapping: <<name>>
    sort_title: <<sort_title>>
    summary: <<summary>>
collections:
  Cosmos Collection:
    template:
      name: Collection - Shows
      show: '58474, 1430'
      summary: >-
        If you wish to make an apple pie from scratch, you must first invent the
        universe.
  Planet Earth Collection:
    template:
      name: Collection - Shows
      show: '1044, 68595'
      summary: Prepare to see it as never before.
  Star Trek:
    template:
      name: Collection - Hide
      show: 137895
      summary: 'Live long, and prosper'
  Star Wars:
    template:
      name: Collection - Trakt List
      list: star-wars-collection
      summary: May the Force Be with You
